### ISSUE TITLE
Medium size file fails to apply (OECD)

### ISSUE THREAD

**Issue by szeke** [usc-isi-i2/t2wml#101]
The following example will cause the GUI to spin for a long time and eventually time out.

Files: [oecd-bug.zip](https://github.com/usc-isi-i2/t2wml/files/4739412/oecd-bug.zip)

Things work properly with a few rows from the file.

**Comment by devowit** [comment]
I was not able to reproduce this error. the yaml file only specifies a few rows-- did you mean to include a yaml file with all the rows?

**Comment by devowit** [comment]
even with the region set to D6:K134 I was still not able to reproduce the eventual timing out (although processing did take a long time, I got results)

**Comment by szeke** [comment]
Now I get results too.
