### ISSUE TITLE
Support uploading properties in KGTK format

### ISSUE THREAD

**Issue by szeke** [usc-isi-i2/t2wml#103]
Currently, properties must be uploaded in JSON. We need support to upload properties in KGTK TSV format as in the attached file. The idea is that the T2WML backend will scan the uploaded file to select rows of the form:
```
	P2006050001	data_type	quantity
	P2006050002	data_type	quantity
```

The set of property types are, the following, using the terminology in the KGTK command to generate triples. We may need to change or add aliases to this list:
```
item
time
globe-coordinate
quantity
monolingualtext
string
external-identifier
url
property
```

**Comment by szeke** [comment]
This command is working, close?

**Comment by devowit** [comment]
sure
