### ISSUE TITLE
KGTK download should put the dates in quotes

### ISSUE THREAD

**Issue by szeke** [usc-isi-i2/t2wml#104]
The value in `node2;kgtk:date_and_time` should be enclosed in `"` as `"2011-01-01T00:00:00"`

**Comment by devowit** [comment]
are there any other fields that should be enclosed in quotes, while I'm at it? (maybe indicate it in Data Types And Their Attributes doc)

**Comment by devowit** [comment]
(right now the code encloses nothing in quotes unless explicitly told to)

**Comment by szeke** [comment]
Yes, `unit`, `text`, `language`,

**Comment by devowit** [comment]
changed in commit ffc2a00

**Comment by devowit** [comment]
as mentioned in 109, units will no longer be enclosed in quotes (once 109 is fixed and closed)
