### ISSUE TITLE
Timeout while applying YAML to large file

### ISSUE THREAD

**Issue by szeke** [usc-isi-i2/t2wml#106]
The `WGI_Data.csv` in https://github.com/usc-isi-i2/t2wml-projects/tree/master/wgi is to large to apply and it times out.

The `template-output` filter contains the `kgtk_properties.tsv` file for the project, use `consolidated_wikifier.csv`, and also load properties from https://github.com/usc-isi-i2/datamart-schema/blob/master/properties.tsv

BTW, I have another file that is 10x larger (195M) which uses the same YAML and wikifier.

**Comment by devowit** [comment]
@szeke could you send us the files for this again? we're just curious to see if @g1eb 's table can handle files agGrid couldn't (not prioritizing adding support if it can't, just curious)
