### ISSUE TITLE
more limited invocations of date_parser

### ISSUE THREAD

**Issue by devowit** [usc-isi-i2/t2wml#110]
as date parsing is expensive it should not be invoked if user specifies date format and ordinary parsing yields a date

**Comment by saggu** [comment]
@devowit  how do I test this?

**Comment by devowit** [comment]
good question. this honestly should be tagged as optimization, not enhancement, it's meant as a performance booster and i think the only way to test would be to benchmark before and after and see if there's an improvement. I guess just close it for now?
