### ISSUE TITLE
Zero value skipped

### ISSUE THREAD

**Issue by kyao** [usc-isi-i2/t2wml#113]
Zero valued cells should not be skipped.
![image](https://user-images.githubusercontent.com/1087657/85232541-6056ae00-b3b4-11ea-9d85-b63345bf49ac.png)

Data file:
[AMIS_Data.xlsx](https://github.com/usc-isi-i2/t2wml/files/4810068/AMIS_Data.xlsx)

Wikifier and property files:
[amis.zip](https://github.com/usc-isi-i2/t2wml/files/4810060/amis.zip)

**Comment by devowit** [comment]
fixed in eab5878
