### ISSUE TITLE
output kgtk (tsv) file not correct if generated from GUI

### ISSUE THREAD

**Issue by ckxz105** [usc-isi-i2/t2wml#117]
If clicked the `download` button on t2wml gui (version 2.0a18), the output tsv file will lost the file name (or dataset id)

The ooutput will be something like:
id | node1 | label
-- | -- | --
.;D6 | Q31 | POECD-002
  | .;D6 | P585
  | .;D6 | P248
  | .;D6 | P2006020004
.;D7 | Q31 | POECD-003
  | .;D7 | P585
  | .;D7 | P248
  | .;D7 | P2006020004
.;D8 | Q31 | POECD-004

Those  id will be no longer unique if second file is generated.

However, if run with script, the output will contains the ID like this, which looks correct

id | node1 | label
-- | -- | --
OECD-Belgium g2g9e450-en.csv;D6 | Q31 | POECD-002
  | OECD-Belgium g2g9e450-en.csv;D6 | P585
  | OECD-Belgium g2g9e450-en.csv;D6 | P248
  | OECD-Belgium g2g9e450-en.csv;D6 | P2006020004
OECD-Belgium g2g9e450-en.csv;D7 | Q31 | POECD-003
  | OECD-Belgium g2g9e450-en.csv;D7 | P585
  | OECD-Belgium g2g9e450-en.csv;D7 | P248
  | OECD-Belgium g2g9e450-en.csv;D7 | P2006020004

**Comment by devowit** [comment]
fixed in commit 5403a8c8
