### ISSUE TITLE
Allow expressions when specifying a region

### ISSUE THREAD

**Issue by szeke** [usc-isi-i2/t2wml#12]
For example, the following should be valid:
```
  region:
    - left: A-1
```

**Comment by bhatiadivij** [comment]
Support added for expressions when specifying a region. 
How should that case be handled when the data region overlaps with the qualifier region.
For Example if the Left attribute is `C-1` It overlaps with the `Gender` Column.
![image](https://user-images.githubusercontent.com/25511720/60844146-4dd86a00-a18d-11e9-8277-7ab3a84dfc12.png)
