### ISSUE TITLE
kgtk output format with wrong data_type

### ISSUE THREAD

**Issue by ckxz105** [usc-isi-i2/t2wml#120]
When testing with AID dataset (Please refered to here at slack https://usc-isi.slack.com/archives/CRJEH62P8/p1594932297168000), the given `kgtk_properties.tsv` specified some nodes like `Paid-security-023` and `Paid-security-024` to be string but t2wml still output the data_type as `quantity`. Please take a look to see what happened there.

appendix: kgtk properties file screenshot
![image](https://user-images.githubusercontent.com/25087508/87726854-b41aa400-c774-11ea-9120-3fc2d9a16725.png)

kgtk output file from t2wml screenshot
![image](https://user-images.githubusercontent.com/25087508/87726920-ceed1880-c774-11ea-9ce1-86efb46468f9.png)

**Comment by devowit** [comment]
String needs to be with an uppercase S
