### ISSUE TITLE
Add more comments and typing hints to functions

### ISSUE THREAD

**Issue by ckxz105** [usc-isi-i2/t2wml#123]
When debugging things, I find that in some files, there is only few or even no comments on what function is used for what. It makes things hard to debug. Please add typing hints for the input / output variables and given some proper comments for functions.

**Comment by devowit** [comment]
I'm happy to do this, and I know it's needed in a lot of places in the code, but if you can tell me where in partcular it would help you I can prioritize adding it there first.

**Comment by devowit** [comment]
I've added a bunch in commit 1ae9b32.
I'm going to close this issue so it's no longer in the active issues tab, but feel free to reopen if you see something unclear that needs additional documentation
