### ISSUE TITLE
Failing to wikify main subject column

### ISSUE THREAD

**Issue by kyao** [usc-isi-i2/t2wml#132]
For version 21, t2wml is failing to wikify main subject column for the aid worker spreadsheet.

[bug.tar.gz](https://github.com/usc-isi-i2/t2wml/files/4968645/bug.tar.gz)

![image](https://user-images.githubusercontent.com/1087657/88336714-57763680-ccea-11ea-9eae-6ee619be85e0.png)

**Comment by kyao** [comment]
Now, this working for me. 
I am not sure what is going on...

**Comment by devowit** [comment]
can you describe the steps you took to cause the bug and the steps taken that caused the bug to disappear? although at first glass my guess would be something weird in a cache somewhere...

**Comment by kyao** [comment]
[bug.tar.gz](https://github.com/usc-isi-i2/t2wml/files/4991662/bug.tar.gz)

I getting a similar error for the executable verstion `t2wml-server.exe` on Windows.

**Comment by kyao** [comment]
Can you take a look to see if you can reproduce the problem with the executable version

**Comment by kyao** [comment]
Tested
