### ISSUE TITLE
Support list of date precisions

### ISSUE THREAD

**Issue by kyao** [usc-isi-i2/t2wml#134]
Automatically select the date precision based on the date format selected.
For example, if the date format selected is "%Y-%m-%d" the precision would be `day`. If the date format selected is "%Y" the precision would be `year`.

```
    - calendar: Q1985727
      format: ['%Y-%m-%d', '%Y-%m', '%Y']
      precision: [day, month, year]
      property: P585
      time_zone: 0
      value: =concat(value[C, $row], value[D, $row], value[E, $row], "-")
```

**Comment by devowit** [comment]
@szeke I seem to recall some discussion about amibiguity over what precision meant, whether it meant precision of duration or precision of time? does this affect the feature request?

**Comment by szeke** [comment]
This feature request makes sense. The precision is the precision of the time.

**Comment by devowit** [comment]
version 2.2.0
