### ISSUE TITLE
Empty cells are not being skipped in version 21, it is working in version 19

### ISSUE THREAD

**Issue by saggu** [usc-isi-i2/t2wml#136]
It should be easy to reproduce, the input file and the yaml file is attached

[Archive.zip](https://github.com/usc-isi-i2/t2wml/files/4998092/Archive.zip)

**Comment by devowit** [comment]
fixed in ec69a17

**Comment by saggu** [comment]
Please give me a chance to test before closing the issue.

**Comment by saggu** [comment]
This issue can be closed after the next release
