### ISSUE TITLE
Integrate Code coverage for t2wml

### ISSUE THREAD

**Issue by saggu** [usc-isi-i2/t2wml#137]
Please see the documentation - https://docs.coveralls.io/

This integration is helpful in determining what percentage of code is covered by the unit tests.

Let us know if you need help.

**Comment by zmbq** [comment]
Added to t2wml and t2wml-api. Github README page shows coverage for master branch, so check this after merging to master.

**Comment by zmbq** [comment]
Coverage calculated during tests and updates the coveralls server. There is a known github issue (https://github.com/lemurheavy/coveralls-public/issues/971) that prevents the badge from always being updated. I've added the suggested workaround, hopefully we will not encounter it.

In any case, if the badge isn't updated and you want to see the actual coverage, just click on the badge and you'll see the report.

**Comment by devowit** [comment]
tested working, aside from github glitches not in our control
