### ISSUE TITLE
Undefined Backend Error: URITooLong

### ISSUE THREAD

**Issue by kyao** [usc-isi-i2/t2wml#141]
I getting an URITooLong error trying to upload a wikifier file.

![image](https://user-images.githubusercontent.com/1087657/89234069-f1b66400-d59f-11ea-9c54-e4846d2d2d57.png)

Here is the file:
[consolidated-wikifier.zip](https://github.com/usc-isi-i2/t2wml/files/5019163/consolidated-wikifier.zip)

**Comment by kyao** [comment]
If the wikifier file size is reduced, then the upload works

**Comment by devowit** [comment]
i have tried to reproduce this bug with the attached file but did not succeed, it works fine for me.

**Comment by kyao** [comment]
Cannot reproduce in development environment. Close for now.
