### ISSUE TITLE
Object of type Timestamp is not JSON serializable

### ISSUE THREAD

**Issue by kyao** [usc-isi-i2/t2wml#144]
Get `Object of type Timestamp is not JSON serializable` error when trying to apply yaml.

Columns K, L and M are stored as Timestamp objects by Pandas. They probably should be converted to str.

![image](https://user-images.githubusercontent.com/1087657/89584971-de9ad280-d7f1-11ea-9c62-5dad1aba7202.png)

[timestamp.tar.gz](https://github.com/usc-isi-i2/t2wml/files/5038109/timestamp.tar.gz)

**Comment by devowit** [comment]
the folder doesn't include the yaml file used to reproduce the bug, can you please send that as well?

**Comment by kyao** [comment]
[t2wml.zip](https://github.com/usc-isi-i2/t2wml/files/5058199/t2wml.zip)

Here is the yaml file

**Comment by devowit** [comment]
fixed in usc-isi-i2/t2wml-api@719b6276a

**Comment by kyao** [comment]
This issue can be closed after the next release
