### ISSUE TITLE
Create basic Electron package

### ISSUE THREAD

**Issue by zmbq** [usc-isi-i2/t2wml#148]
No UI, it should just run the Flask backend and access localhost:13000 inside Electron.

Add the proper packaging flow, so we have an Electron based installation

**Comment by zmbq** [comment]
Version 2.3 has a working Electron setup, with a proper packaging flow.

**Comment by saggu** [comment]
There is an electron package. Unless there is something else pending related to this particular issue, @zmbq feel free to close
