### ISSUE TITLE
Fix ids in the downloaded KGTK file from T2WML

### ISSUE THREAD

**Issue by saggu** [usc-isi-i2/t2wml#151]
Files to reproduce

[issue_151.tar.gz](https://github.com/usc-isi-i2/t2wml/files/5059718/issue_151.tar.gz)

1. Input data file - 04_worker_incidents.xlsx
2. upload properties - properties.tsv, kgtk_properties.tsv
3. wikifier - consolidated-wikifier.csv
4. Item definitions - extra_edges.tsv, kgtk_units.tsv, kgtk_variables.tsv
5. yaml - t2wml.yaml

**Comment by saggu** [comment]
Seems to be working from the `development` branch.

I have a clarification question @devowit 

Why are the ids for qualifier edges blank ? Is this a conscious decision?

![image](https://user-images.githubusercontent.com/6811931/90080304-1bb60780-dcbf-11ea-9f8c-975e5f85ab22.png)

**Comment by devowit** [comment]
re @saggu yes it was a conscious decision, I designed it according to specs from @szeke 
if the specs have changed, let me know.

**Comment by saggu** [comment]
Nope, specs are still the same. Thanks for clarifying
