### ISSUE TITLE
T2WML is caching labels in wikifier

### ISSUE THREAD

**Issue by saggu** [usc-isi-i2/t2wml#154]
Again, you can reproduce this issue by using the attached zip
[t2wml-training.zip](https://github.com/usc-isi-i2/t2wml/files/5060871/t2wml-training.zip)

Steps to reproduce.
1. Upload data file , properties, item definitions, and wikifier
2. change a label for any row in the item definition file and upload again
3. Notice that the label for changed row is `cached` and not updated until we reload the project

**Comment by devowit** [comment]
I've moved this back to priority 2, because:
1. it's a cosmetic issue that only affects the display of labels to user
2. it is easily resolved simply by reloading the page

Priority 1 bugs should, I think, be more critical than that...

**Comment by saggu** [comment]
@devowit I agree with this being a P2, I assigned it a P1 by mistake.

However, this is not merely a cosmetic issue. Cosmetic issues are for eg: `a button is misaligned` or `typo in some label`.

Pedro was trying to upload a new label for a property and the Wikifier UI did not update. We had to reload to see it actually change.

**Comment by devowit** [comment]
wait, he was uploading a label for property, or a label for wikifier (item)? because labels for properties are updated when uploading a properties file, not when uploading a wikifier file. (we can change this behavior if you think it's necessary, but that's how it works right now)

in any case, i thought labels do not get output to the download/calculation data? that's what I meant by cosmetic issue-- an issue seen only by human eyes viewing the GUI, not reflected in the actual calculation results...

**Comment by szeke** [comment]
The label would not change even after reloading.

**Comment by devowit** [comment]
I have tried reproducing this on windows and on ubuntu without any success

**Comment by saggu** [comment]
I am testing this in version 2.3.3
I tried updating the label in wikifier, properties and item definitions files. The label is not updating even after reloading.

We should really merge wikifier, properties and item definitions files. It is unclear updating which file affects what.

Re opening

**Comment by devowit** [comment]
I am moving this back to ready for testing now that we've switched to a merged button for properties and items, although I am not sure if the bug is fixed as I still can't reproduce it. I guess the next step if is to check if it's somehow OS-specific, although I can't imagine why...

**Comment by devowit** [comment]
@saggu  any updates on this one?

**Comment by saggu** [comment]
Closing, will open a new issue if required
