### ISSUE TITLE
Database gets corrupted when switching tabs back and forth in homicides example

### ISSUE THREAD

**Issue by szeke** [usc-isi-i2/t2wml#156]
To reproduce load the homicides file, upload all the request wikifier, etc files, and then start adding yawls for the different tabs. Then switch to previously entered tabs, and keep doing this. Eventually the display is corrupted showing incorrect highlighting, and then a database error as in 

<img width="987" alt="image" src="https://user-images.githubusercontent.com/1074599/89983861-448dbc80-dc2d-11ea-9c39-5f80a459bf79.png">

Sometimes you can switch to the previous tabs, but it looks like it applies the incorrect YAML, as in

<img width="987" alt="image" src="https://user-images.githubusercontent.com/1074599/89983931-65eea880-dc2d-11ea-92fa-80456633d786.png">

**Comment by devowit** [comment]
the  main bug is fixed in 9d64a08f, a side bug (the database error) is fixed in bcfff511

**Comment by devowit** [comment]
version 2.2.0
