### ISSUE TITLE
enable skip_cells-like functionality for qualifiers as well

### ISSUE THREAD

**Issue by devowit** [usc-isi-i2/t2wml#158]

**Comment by saggu** [comment]
This might be a duplicate of #149

**Comment by devowit** [comment]
it's not, but looking at that issue was what reminded me to add this one.
this one is adding a syntax feature, that one is modifying the kgtk generation code.

**Comment by devowit** [comment]
overlaps with #279

**Comment by devowit** [comment]
with #279 added, skip_cells is supported. close when tested in version 2.4.0
