### ISSUE TITLE
Enable shortcuts in MacOS (and other OS) applications

### ISSUE THREAD

**Issue by saggu** [usc-isi-i2/t2wml#168]
At the very least, the following commands should work

1. command (ctrl for windows) x - cut
2. command (ctrl for windows) c - copy
3. command (ctrl for windows) v - paste
4. command (ctrl for windows) z - undo

**Comment by zmbq** [comment]
Fixed, will be in the next release (2.3.3)

**Comment by saggu** [comment]
Confirming that the 4 mentioned shortcuts are working in 2.3.3 in the yaml section.

Closing
