### ISSUE TITLE
New Feature: Upload to Datamart API

### ISSUE THREAD

**Issue by saggu** [usc-isi-i2/t2wml#170]
For annotated spreadsheets only, we need a new button besides `Download`, to be able to upload to Datamart,

On clicking the `upload` button,
1. read the `{dataset_id}` from cell `B1`
2. check if the dataset exists in Datamart`: `/metadata/datasets/{dataset_id}`
3. Intimate users if the dataset does not exist
4. If the dataset exists, Upload the `KGTK` file to the url : `/datasets/{dataset_id}/t2wml`
This url exists, but needs some to be able to accept the KGTK file from t2wml as it is being generated right now

**Comment by saggu** [comment]
Sending the item definitions and kgtk data file combined is not going to work because they do not have the same columns.

Please change so that the API sends multiple files as we discussed in the meeting today, like so
```
files = {
            'kgtk_output': (Path(str(tmpfile.name)).name + '.tsv', tmpfile, 'application/octet-stream'),
            'item_definitions_all': (<some other name> + '.tsv', <items file>, 'application/octet-stream'),
        }
```

**Comment by saggu** [comment]
3. Intimate users if the dataset does not exist 
is not implemented. In annotation-integration branch

**Comment by devowit** [comment]
@talyashra  we need to add an alert to the user

**Comment by devowit** [comment]
@saggu  added uload dataset and added proper notification, so this issue is sort of moot/ changed

**Comment by saggu** [comment]
Closing this issue, all the actions items in this are complete
