### ISSUE TITLE
When selecting "add new project", auto-focus the text-box

### ISSUE THREAD

**Issue by devowit** [usc-isi-i2/t2wml#172]
Instead of clicking "new project" and then having to move and click the text box to enter the project name, the text box should be autofocused so that user can immediately start typing the name

**Comment by kyao** [comment]
Still does not autofocus, at least on my linux box

**Comment by saggu** [comment]
This is working in 2.3.3. Currently `New Project` has stopped working. I will create a new issue for that.

Closing this one
