### ISSUE TITLE
Output section should show the units as well, if present

### ISSUE THREAD

**Issue by saggu** [usc-isi-i2/t2wml#174]
Specifically here,

![image](https://user-images.githubusercontent.com/6811931/90556010-12102200-e14d-11ea-9aca-1486133cfcaf.png)

**Comment by dgarijo** [comment]
I also experienced this error on the Windows executable.

**Comment by saggu** [comment]
@dgarijo this is an enhancement, does not exist yet :)

**Comment by dgarijo** [comment]
Ok, when I was using this I thought it was a little disorienting: I didn't know whether my units had been correctly interpreted until I downloaded the results.

**Comment by saggu** [comment]
Working in 2.3.3. Closing
