### ISSUE TITLE
Download results always displays an error, even if there is no error

### ISSUE THREAD

**Issue by dgarijo** [usc-isi-i2/t2wml#175]
**Describe the bug**
Every time I download a result (JSON) I see the following in the UI:
![image](https://user-images.githubusercontent.com/1520666/90582137-e0657e00-e181-11ea-9d18-1e7510baaf69.png)

However, when I inspect the results, they have been downloaded correctly.

**To Reproduce**
1. Set up a project.
2. Download results

**Expected behavior**
The error should not appear

**Desktop (please complete the following information):**
Using Windows executable in v2.1.1

**Comment by devowit** [comment]
Were there errors in the individual cells? (was everything colored green, or were there some orange/red cells?)
Although you say it is every time, could you please attach one set of files where it happens?
Thank you

**Comment by dgarijo** [comment]
There were no errors in the individual cells, all were colored green:
![image](https://user-images.githubusercontent.com/1520666/90665331-bdc67a00-e200-11ea-89b8-5fef6a415980.png)

I attach a sample set of files were this happen.
[06_region_annotated.xlsx](https://github.com/usc-isi-i2/t2wml/files/5097941/06_region_annotated.xlsx)

The yaml, properties.tsv and wikifier can be seen in the tutorial folder of this repository. Many other examples can be seen there (same error happened in all of them)

https://github.com/usc-isi-i2/t2wml/blob/master/tutorial/properties.tsv
https://github.com/usc-isi-i2/t2wml/blob/master/tutorial/wikifier.csv
https://github.com/usc-isi-i2/t2wml/blob/master/tutorial/annotated_yaml/06_region.yaml

**Comment by devowit** [comment]
should be fixed in 2.3.7, please close once tested

**Comment by saggu** [comment]
@dgarijo please test and close

**Comment by devowit** [comment]
assuming no update means this was fixed, reopen if i'm wrong
