### ISSUE TITLE
Scroll bar is too thin to select it properly

### ISSUE THREAD

**Issue by dgarijo** [usc-isi-i2/t2wml#178]
When I have multiple sheets open, it is very difficult to select the scroll bar, because it's too thin (see below)

![image](https://user-images.githubusercontent.com/1520666/90693087-127eea80-e22b-11ea-8ad3-1a7fd54919f1.png)

It would be great to make the scroll bar bigger so you can move around your spreadsheets with ease.

Tried on the Windows executable v2.1.1

**Comment by devowit** [comment]
should be fixed in 2.3.7, please close once tested

**Comment by saggu** [comment]
The scroll bar is thick enough. Closing
