### ISSUE TITLE
t2wml specification file

### ISSUE THREAD

**Issue by dgarijo** [usc-isi-i2/t2wml#18]
Could it be linked from the readme of the project? It's a little complicated to know which are the supported functions (e.g., to skip rows) if the the spec is not available

**Comment by bhatiadivij** [comment]
I have pushed a new build. 
This build supports the following spec:
`ValueExpressions: value($col/$row)`, 
`ItemExpressions: item($col/$row)`, 
`BooleanEquations: value(C/$row) = "Females" and item(A/$row) = "Q9707" -> value($col/$row)`, 
`BooleanExpressions: value(C/$row) = "Females" and value(A/$row) contains "Buru" ` 

Nesting of these functions is also allowed
For Example: 
`value(value(C/$row) = "Females" -> $col/$row)`

I have added support for `skip_row` and `skip_column` attributes. These attributes take BooleanExpression as value 
For Example:
`skip_row: value(A/$row) = "" `
`skip_column: value($col/3) = "2002" `

**Comment by bhatiadivij** [comment]
Region and cell expressions can be defined as a mathematical expression.
For example:
```left: C+1
right: G-1
top: 5+1
bottom: 8+1
value($col+1/$row+1)```

Variables are not supported in any of the cell expressions.
For example:
```value($col/$row-n)``` This expression is not supported

**Comment by dgarijo** [comment]
If you add these to the readme then you can close this issue.
You can add something like "Supported operations" or something like that.

**Comment by szeke** [comment]
Closing, we need a user guide.
