### ISSUE TITLE
Get installer working

### ISSUE THREAD

**Issue by devowit** [usc-isi-i2/t2wml#188]
A standalone executable for Windows, Mac and Linux is created automatically when tagging a commit with v* .

Work is in progress for an Electron based installation.

**Comment by zmbq** [comment]
Version 2.3 has an Electron installer working.

**Comment by saggu** [comment]
Installer is creating with a release. Are we tracking other installer related issues separately?

**Comment by devowit** [comment]
yes, please create new issues for other problems with the installer @saggu

**Comment by devowit** [comment]
(and i guess we can close this one, if the installer is "working"-- ie builds automatically, installs on all three systems)
