### ISSUE TITLE
import/export project

### ISSUE THREAD

**Issue by devowit** [usc-isi-i2/t2wml#189]
requested by @szeke in #180, moving to its own issue

The desired capability:

Project export button: saves a zip file with a project, user can save it anywhere they want
Project import: import a zip file that was saved using export:
If the project is new, create it
If the project exists, give the user the option to overwrite or cancel.

**Comment by devowit** [comment]
We should test that importing directories is working as expected, and then everything else in this issue we've decided won't be directly t2wml functionality-- zipping/unzipping files-- the user will just do that on their own.

**Comment by devowit** [comment]
version 2.3.4
please close when tested ok

**Comment by saggu** [comment]
Cannot be tested properly until #247 is fixed

**Comment by devowit** [comment]
should be checked now that #247 is fixed
