### ISSUE TITLE
etk library installation

### ISSUE THREAD

**Issue by naomiperez** [usc-isi-i2/t2wml#19]
After following the installation instructions from the readme and running application.py, I got a ModuleNotFoundError for 'etk.wikidata' on line: 'from etk.wikidata.entity import WDItem' (from the triple_generator.py file). 
I think that the etk library (https://github.com/usc-isi-i2/etk) that downloads from the requirements.txt installation process doesn't contain WikiData modules. Instead I have tried installing https://github.com/fatestigma/etk/tree/wikidata which does contain WikiData modules, but the file structure doesn't match the imports in the code.

**Comment by GreatYYX** [comment]
try on development branch

**Comment by naomiperez** [comment]
I uninstalled the etk library and installed the development branch "https://github.com/usc-isi-i2/etk@development" instead, which resolved the issue.
