### ISSUE TITLE
define download functionality in annotation-integration

### ISSUE THREAD

**Issue by saggu** [usc-isi-i2/t2wml#191]
1. Rename the `Download` button to `Download Canonical Data`
2. Clicking the `Download Canonical Data` should get the file using the URL as returned by `Upload to Datamart` button

**Comment by devowit** [comment]
okay so step one a person uploads a file, efinitions are automatically created.
step two, they can upload to datamart. this returns a URL. 
step three, they can download from the URL

is that URL something they should be able to access if they close the program and reopen it? in other words, does it need to be saved somewhere? can someone expect, after uploading to datamart, to always be able to download canonical data for that project?

**Comment by saggu** [comment]
@devowit your assumptions are correct, the url needs to be saved. Every time the user tweaks the data and uploads to Datamart a url will be returned which should then be saved.

One more thing, the download button should be disabled if there is no url to download from., ie, the user has not uploaded anything

**Comment by devowit** [comment]
just to clarify, this means getting rid of the current Download button (the one with tsv and json) and replacing it with the download canonical data button?

**Comment by saggu** [comment]
@devowit since the code base is merged into `development`. We need to change T2WML a bit:
If there is a file `local_settings.py` with `annotation_integration=True` ,
   - Switch the regular Download button with `Download Canonical Data`
   - This button's download changes according to the current active sheet in T2WML GUI

**Comment by devowit** [comment]
>Switch the regular Download button with Download Canonical Data

This is complicated. It would actually be easier to have the same download dialogue, and add "Canonical data" to the dropdown options for format. Is that ok?

>This button's download changes according to the current active sheet in T2WML GUI

...this should anyway be how it would behave, no?

**Comment by saggu** [comment]
>This is complicated. It would actually be easier to have the same download dialogue (as we already have in the main branch), and add "Canonical data" to the dropdown options for format. Is that ok?

 Yup that is fine.

>...this should anyway be how it would behave, no?

It should, but T2WML needs to store the download urls for each sheet, which it is not yet doing.
