### ISSUE TITLE
Error when I close (not quit) the T2WML and open it again

### ISSUE THREAD

**Issue by saggu** [usc-isi-i2/t2wml#192]
To reproduce (in mac):

1. Close the application using the `red` close button
2. Click the application icon in the Dock again to open it
3. See the error
![image](https://user-images.githubusercontent.com/6811931/91910607-2f241500-ec64-11ea-9c7d-84570c48a88a.png)
4. Clicking on ok, resumes normal operation

**Comment by saggu** [comment]
This issue is still present in 2.3.3

**Comment by zmbq** [comment]
Fixed in version 2.3.4

**Comment by saggu** [comment]
Fixed indeed. Closing
