### ISSUE TITLE
Support Ethiopian Calendar

### ISSUE THREAD

**Issue by kyao** [usc-isi-i2/t2wml#193]
If in the yaml the `calendar` is `Q215271`, the `value` is in Ethiopian calendar format. Convert the value to Gregorian calendar.

**Comment by devowit** [comment]
you've mentioned a specific library that does conversions of ethiopian to gregorian, could you link me it please? thank you

**Comment by kyao** [comment]
Here is the python library: https://github.com/dimagi/ethiopian-date-converter

**Comment by devowit** [comment]
ok so if `calendar:` trait is set to `Q215271` then use the converter? any other things it could be set to that would invoke the converter?

**Comment by devowit** [comment]
I just tried to do `pip install ethiopian_date` as described in their README, and got an error 

```
    ERROR: Command errored out with exit status 1:
     command: 'c:\users\devora\c_sources\pedro\t2wml-api\env\scripts\python.exe' -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\devora\\AppData\\Local\\Temp\\pip-install-s0n85fcd\\ethiopian-date\\setup.py'"'"'; __file__='"'"'C:\\Users\\devora\\AppData\\Local\\Temp\\pip-install-s0n85fcd\\ethiopian-date\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base 'C:\Users\devora\AppData\Local\Temp\pip-pip-egg-info-8s2eu8bq'
         cwd: C:\Users\devora\AppData\Local\Temp\pip-install-s0n85fcd\ethiopian-date\
    Complete output (7 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\devora\AppData\Local\Temp\pip-install-s0n85fcd\ethiopian-date\setup.py", line 9, in <module>
        version=__import__('ethiopian_date').__version__,
      File "C:\Users\devora\AppData\Local\Temp\pip-install-s0n85fcd\ethiopian-date\ethiopian_date\__init__.py", line 27, in <module>
        from ethiopian_date import EthiopianDateConverter
    ImportError: cannot import name 'EthiopianDateConverter' from 'ethiopian_date' (C:\Users\devora\AppData\Local\Temp\pip-install-s0n85fcd\ethiopian-date\ethiopian_date\__init__.py)
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```

it looks like there's something wrong with the package. Were you able to successfully install/run it?

**Comment by kyao** [comment]
Just the calendar trait, if it is set to Q215271 then use the converter.
```
    qualifier:
    - calendar: Q215271
```

**Comment by szeke** [comment]
Is the idea that the output will contain the data in Gregorian format? Will it have both dates? I think we need a `date conversion` setting in T2WML with values: `keep original`, `replace with Gregorian`, `add Gregorian`

**Comment by kyao** [comment]
How about always convert to Gregorian, and then also have the option of keeping the original?

Not having a Gregorian calendar date would make more querying difficult. We would have to check of the calendar type before querying.

**Comment by szeke** [comment]
Ok, we can have `replace with Gregorian` as the default. T2WML is a general purpose tool, so we need to implement features in a generic way.

**Comment by kyao** [comment]
KGTK does not directly support calendar. How about introducing a new property `PCalendar`?

Below is a statement `e1` with two point in time `P585` qualifiers. The first `P585` statement is qualified with the the Ethiopian calendar `Q215271` and the second is qualified with Gregorian calendar `Q12138`.
```
id      node1   label   node2
e1      Q3513939        PVARIABLE-QEth-census-partial-002       1089.21
e2      e1      P585    ^2012-13-01T00:00:00/9
e3      e2      PCalendar       Q215271
e5      e1      P585    ^2020-09-06T00:00:00/9
e6      e5      PCalendar       Q12138
```

**Comment by szeke** [comment]
@kyao There is no need for a calendar property. The exploded file has the following columns, the calendar goes in `node2;calendar` 

```
(base) D22ML-PSZEKELY:wikidata-20200803-v2 pedroszekely$ gzcat wikidata-20200803-all-edges.tsv.gz | head
id	node1	label	node2	rank	node2;magnitude	node2;unit	node2;date	node2;item	node2;lower	node2;upper	node2;latitude	node2;longitude	node2;precision	node2;calendar	node2;entity-type	node2;wikidatatype
```

**Comment by devowit** [comment]
Ok, I am now fully lost. Given the discussion above, what is the feature we want implemented?

**Comment by kyao** [comment]
Here is my understanding. 
```
    qualifier:
      - calendar: Q215271
        date conversion: keep original
```
The T2WML snippet above says that the dates in the data is in Ethiopian calendar format. And, T2WML should generate two date qualifiers for each statement. One date qualifier in Gregorian, and one date qualifier in Ethiopian calendar. The exploded tsv should look something like below. Edge e2 is date qualifier in Gregorian, and Edge e3 is qualifier in Ethiopian.
```
id      node1   label   node2   node2;date      node2;calendar
e1      Q3513939        PVARIABLE-QEth-census-partial-002       1089.21
e2      e1      P585            2020-01-01T00:00:00     Q12138
e3      e1      P585            2012-13-01T00:00:00     Q215271
```

The other `date conversion` setting is `replace with Gregorian`. For this setting Edge e3 will not be generated.

If no `date conversion` is specified, then the default behavior is `replace with Gregorian`.

**Comment by zmbq** [comment]
The terms are a little confusing to me. "replace with Gregorian" makes sense, but it's not intuitive for me that "keep original" keeps the original AND converts to Gregorian. I would expect "keep original" to just keep the original, without creating an additional edge. Also, there is no option for keeping the original without creating an additional edge.

Do note that as it stands, "keep original" will cause Datamart to malfunction, returning two rows for each data point, as we join on the P585 label. We need to figure out how to handle multiple P585 edges in Datamart.

**Comment by szeke** [comment]
Keep original means to do nothing, ie no changes to the user input.

I was thinking that date conversion is a global setting, not something that the user has to put in the YAML. 

I agree with @zmbq that add Gregorian will cause the queries to return two items, so we should not use it in Datamart, but it still makes sense to have the option

**Comment by devowit** [comment]
@kyao can i have an example project for this?

**Comment by devowit** [comment]
should be supported in 2.3.10, close if working as expected

**Comment by devowit** [comment]
assuming no response for months means it's been dealt with, closing
