### ISSUE TITLE
Bring back the ability to create New Project

### ISSUE THREAD

**Issue by saggu** [usc-isi-i2/t2wml#195]
**Describe the bug**
`New Project` button on the home screen is not working. I know this is expected behavior at this point, but we 
want this functionality back.

**To Reproduce**
1. Open T2WML application
2. Click on `New Project'
3. Type in the project name and press `Create`

**Screenshots**
![image](https://user-images.githubusercontent.com/6811931/92163557-c2865300-ede8-11ea-9653-1f56889c7559.png)

**Desktop (please complete the following information):**
 - OS: mac
 - Version: 2.3.3

**Comment by devowit** [comment]
version 2.3.4
please close when tested ok

**Comment by saggu** [comment]
Working in 2.3.4. Closing
