### ISSUE TITLE
Creating new project using File menu takes the user back to previous project

### ISSUE THREAD

**Issue by saggu** [usc-isi-i2/t2wml#196]
**To Reproduce**
1. Open T2WML application
2. Open any existing project
3. go back to the All Projects screen by clicking the icon in top left corner
4. Click File->New Project or press ⌘N, choose a folder and click `Open`
5. See error: I am taken back to the previous project screen

**Expected behavior**
I should see the project details window of the newly created project with blank datasheet and yaml etc

**Desktop (please complete the following information):**
 - OS: mac
 - Version 2.3.3

**Comment by devowit** [comment]
this should have been fixed in later versions, but it didn't get added to the bugs and issues project so I didn't see it to close it
