### ISSUE TITLE
Display Project Name in the black bar adjacent to T2WML icon

### ISSUE THREAD

**Issue by saggu** [usc-isi-i2/t2wml#197]
Instead of showing this at Application Top bar (marked by blue arrow), it should be displayed as shown in Red
![20200903_134536](https://user-images.githubusercontent.com/6811931/92165451-f1ea8f00-edeb-11ea-8126-7546a775c844.jpg)

**Comment by talyashra** [comment]
Done in 'development',

**Comment by devowit** [comment]
version 2.3.4
please close when tested ok

**Comment by saggu** [comment]
Working in 2.3.4. Closing
