### ISSUE TITLE
Pressing ⌘R takes me to All Projects Window instead of Reloading the current Project

### ISSUE THREAD

**Issue by saggu** [usc-isi-i2/t2wml#198]
**Describe the bug**
See Title

**To Reproduce**
1. Open T2WML application and open an existing project
2. Press ⌘R to reload the project view
3. It takes me to the `All Projects` window instead

**Expected behavior**
The current window should be refreshed

**Desktop (please complete the following information):**
 - OS: mac 
 - Version 2.3.3

**Comment by zmbq** [comment]
⌘R is for debugging purposes only, as is the Developers Tools option. If we want people to be able to refresh the project, we should add a non-debug option for this - a button on the project page or in a menu.

Why would a user want to reload a project, though?

**Comment by szeke** [comment]
An option for debugging is useful. It doesn't have to be a keyboard shortcut. Reloading may be useful when things go wrong.

**Comment by devowit** [comment]
commit fa2be7d

**Comment by zmbq** [comment]
We've added a Project menu with a Refresh option (which is tied to F5 or Cmd-R) - this option does what you expect it to do. The Debug menu now has a "Reload App" option with no keyboard shortcut which we will use for debugging.

**Comment by devowit** [comment]
version 2.3.4 (please close once tested OK)

**Comment by saggu** [comment]
Working in 2.3.4. Closing
