### ISSUE TITLE
Installer is big and slow

### ISSUE THREAD

**Issue by devowit** [usc-isi-i2/t2wml#201]
After transition to electron, the installer became inexplicably much bigger, and takes a long time to install

**Comment by zmbq** [comment]
The electron-builder builder takes all the prod dependencies from package.json and adds them to the installation, even though webpack already takes care of everything. It is very important not to add prod dependencies, use `yarn add --dev` to add more packages.

**Comment by devowit** [comment]
version 2.3.4
please close when tested ok

**Comment by saggu** [comment]
The application size is now 164 MB. Closing
