### ISSUE TITLE
Make entity definitions project-specific

### ISSUE THREAD

**Issue by devowit** [usc-isi-i2/t2wml#202]
right now entity definitions are shared across projects

**Comment by devowit** [comment]
@saggu  this isn't complicated to apply for user-uploaded definitions. But what about definitions queried from sparql? Do we want those also to only be applied to the active project?

**Comment by szeke** [comment]
We do want entities, properties and wikifier to be project specific. WIth the new project on disk it will be easy to copy these files to new projects.

**Comment by devowit** [comment]
@szeke  ok, so then you also want properties fetched from wikidata to be saved to specific projects? eg P585?

My concern is how does this end up working when uploading to datamart, you can have the same property ID mean two different properties entirely?

**Comment by szeke** [comment]
@devowit Properties present in Wikidata cannot (should not) be overwritten. We are not checking for this, but we could do something easy such as disallowing uploading of properties with the format `Pnum` where `num < 10000`

**Comment by devowit** [comment]
should be added in 2.3.7, please close once tested

**Comment by devowit** [comment]
@szeke  is this working as expected?

**Comment by szeke** [comment]
@saggu please check whether this is working as expected

**Comment by devowit** [comment]
@saggu  can I/you close this?

**Comment by saggu** [comment]
Sorry, should have been closed. Closing now
