### ISSUE TITLE
Display loaded entities to user

### ISSUE THREAD

**Issue by devowit** [usc-isi-i2/t2wml#204]
Right now there is no way for user to see which entity definitions have been added to the current project (can open entity definitions file and read them, but no way to confirm they've been added to project successfully or that some value wasn't overwritten)

**Comment by devowit** [comment]
Proposal: We should add another collapsible tab to the yaml/wikifier pair (to create a trio...)
This tab would be called "Entities", and like wikifier it would display a scrollable table (for now, uneditable, but it should be possible in the future to make it editable). The button for importing entities would be moved to this tab. 
The table would update whenever entities are imported. It should also update after applying a yaml, because the backend can make sparql queries during the application process and those sparql query labels/definitions get added to the entities for that project.

**Comment by devowit** [comment]
@saggu thoughts?

**Comment by szeke** [comment]
Yes, new tab is a good solution. Let's keep this in Prio 2.

**Comment by devowit** [comment]
this ended up being dealt with (somewhat differently than planned) in #332
