### ISSUE TITLE
alert user if trying to create new project where project already exists

### ISSUE THREAD

**Issue by devowit** [usc-isi-i2/t2wml#206]

**Comment by devowit** [comment]
version 2.3.4
please close when tested ok

**Comment by saggu** [comment]
![image](https://user-images.githubusercontent.com/6811931/92630439-b6851000-f284-11ea-9d67-5027c16309fe.png)

Change the message to "A project already exists at this location"

**Comment by devowit** [comment]
Done. I don't think a hardcoded string change requires testing, so I'm closing this issue
