### ISSUE TITLE
fixing spinner in data preview

### ISSUE THREAD

**Issue by devowit** [usc-isi-i2/t2wml#207]
The loading spinner in preview box stops spinning before the preview loads, giving user the impression that the cell has an empty/nonexistent preview. about a second later, the preview loads. The problem is caused by a problem in the async/await mechanism and needs to be fixed properly.

**Comment by devowit** [comment]
This seems to have been fixed, at least when I've checked it.

**Comment by devowit** [comment]
should be fixed in 2.3.7, please close once tested

**Comment by saggu** [comment]
@devowit please close once you have tested it. I am not sure how what are the correct steps to reproduce
