### ISSUE TITLE
Version 2.3.4 locks up

### ISSUE THREAD

**Issue by szeke** [usc-isi-i2/t2wml#208]
<img width="1270" alt="image" src="https://user-images.githubusercontent.com/1074599/92626557-e8937380-f27e-11ea-8d60-dd1dbbfd9c09.png">

I clicked on the red cell, and the spinners come up and it is locked.

**Comment by szeke** [comment]
[tutorial_region_4.zip](https://github.com/usc-isi-i2/t2wml/files/5196639/tutorial_region_4.zip)

Project files. BTW, this is an old project, so there may be something weird going on. This project did work in version 2.3.3

**Comment by devowit** [comment]
related to issue #207, will be fixed at same time

**Comment by devowit** [comment]
I've tried to replicate this bug, but didn't manage. However, when I loaded the project file, I didn;t get red data cells, I got green ones...

**Comment by devowit** [comment]
should be fixed in 2.3.6, close when tested

**Comment by saggu** [comment]
It is not locked anymore in version 2.3.7, but the issue with properties is still there
