### ISSUE TITLE
How to delete a project?

### ISSUE THREAD

**Issue by saggu** [usc-isi-i2/t2wml#209]
The delete button disappeared in version 2.3.4

**Comment by devowit** [comment]
if you delete the project folder, or move it, the project should no longer be displayed. since we've moved to file-based rather than database based. what additional functionality do you need?

**Comment by saggu** [comment]
A delete button which does what for the user would be nice

**Comment by devowit** [comment]
i have added back the project delete button. It deleted the project's entire directory! (it does warn the user in advance)

**Comment by devowit** [comment]
version 2.3.6
