### ISSUE TITLE
Conflicting "lark" namespace

### ISSUE THREAD

**Issue by huerdong** [usc-isi-i2/t2wml#21]
In the requirements.txt file, both lark==0.0.4 and lark_parser==0.7.1 are included, but both use the namespace "lark" for imports, which leads to a confusion where the wrong library gets imported. The only places where the "lark" namespace is used is in t2wml_parser.py where the reference is to lark_parser, so it appears "lark==0.0.4" is not even needed for function. This is a minor inconvenience as one can simply remove the package from the requirements.txt or manually uninstall it, but it's a source of confusion for fresh users.

**Comment by bhatiadivij** [comment]
I have fixed it. Thanks.
