### ISSUE TITLE
Data file uploads to the wrong project

### ISSUE THREAD

**Issue by kyao** [usc-isi-i2/t2wml#213]
**Describe the bug**
In `development` branch data file uploads to the previous project, not the current project.

**To Reproduce**
1. Create a new project.
2. Upload data file, upload wikifier, and import entities
3. Create another new project
4. Upload different data file, wikifier and entities files.

The second data file is uploaded to the first project. The second entities file is also uploaded to the first project.
However, for some reason the second properties file is uploaded correctly to the second project.

**Comment by devowit** [comment]
this was a known bug in 2.3.3. Can you just double check that you were running 2.3.4?
If so, @zmbq, guess we didn't fully solve this...

**Comment by devowit** [comment]
believed to be fixed in 06e2eff

**Comment by devowit** [comment]
sorry for delay in pushing this one to ready for testing, we discovered additional bugs., but it is now merged into development branch and should no longer be an issue.

**Comment by kyao** [comment]
Tested OK

**Comment by saggu** [comment]
Closing as this was tested OK over 2 weeks ago
