### ISSUE TITLE
Validate P/Q definitions

### ISSUE THREAD

**Issue by devowit** [usc-isi-i2/t2wml#220]
Enforce the following restrictions on custom DataEntity definitions:

Custom properties must begin with P, and must be longer than one character
Custom properties with the format Pnum where num<10000 are forbidden

Custom items must begin with Q, and must be longer than one character
Custom items with the format Qnum where num<1 billion are forbidden

**Comment by devowit** [comment]
version 2.3.6, close once tested

**Comment by saggu** [comment]
@devowit quick question: how does T2WML whether a property is custom versus an actual Wikidata property?

**Comment by devowit** [comment]
custom properties are those uploaded by the user.
wikidata properties are those queried by sparql. 
attempting to upload a wikidata property (eg, P585) in the upload entities field will have it treated as a custom property (and it will fail, since by definition wikidata property IDs are "illegal" for custom properties)

**Comment by szeke** [comment]
We need a way to upload the Wikidata properties so that we don't have to query them from Wikidata live. We need T2WML users to be able to work disconnected from the Internet

**Comment by szeke** [comment]
@devowit We should be able to preload entities using a KGTK file, including property type, labels and descriptions. We don't want a custom JSON file. Let's discuss at the meeting.

**Comment by devowit** [comment]
issues #281 and #267 relate to the further discussion, this issue is no longer relevant
