### ISSUE TITLE
Open project does not recognize copied directory on linux

### ISSUE THREAD

**Issue by devowit** [usc-isi-i2/t2wml#223]
Copied from thread of another issue, promoted to its own, reported by @kyao 

The problem is with the filepath separator on Linux.
If I change this line:
https://github.com/usc-isi-i2/t2wml/blob/development/electron/src/main/menu.ts#L141

            const index = result.filePaths[0].lastIndexOf('\\');
to

           const index = result.filePaths[0].lastIndexOf('/');
Then it works

---

(original description of problem:

I create a new project, and copy the files in the project directory to another directory. But,

Open Project` does not seem to recognize the copied directory.)

**Comment by devowit** [comment]
fixed in commit 9aa58bb2

**Comment by devowit** [comment]
version 2.3.6, close once tested

**Comment by saggu** [comment]
@kyao please test this

**Comment by devowit** [comment]
assuming that no further news means the bug is  gone, reopen (and move back to to-do column) if I'm wrong
