### ISSUE TITLE
Add ability to create new Wikidata Items

### ISSUE THREAD

**Issue by devowit** [usc-isi-i2/t2wml#225]
Moving todo's gathered in various places to all live in github issues.
from the initial statement of work:

Add Ability To Create New Wikidata Items:
T2WML must provide the ability to create new Wikidata items using information in the data files
extend the T2WML syntax to add instructions for creating new items
extend the T2WML interpreter to issue the Wikidata commands to create new items.

**Comment by devowit** [comment]
@szeke  @zmbq  @saggu I think we need to discuss this issue a bit more. 
We discussed in the meeting yesterday creating properties and items for everything, "like we do in datamart", and itay mentioned the problem of checking uniqueness depending on which datamart is running. 
can we discuss this further?

**Comment by szeke** [comment]
Related to #290 which is about creating new properties. As discussed in #290, my recommendation is that users can define an external file where the new items will be created. A project can define a mapping from a name to the path of the external file, eg, `wm-items` can be the name and it needs to be resolved to a file name on the local disk. The name eg `wm-items` is stored in the project, and when a different user opens the project, the file name must be resolved. This sounds painful, but we cannot store the new items or properties on the project folder as they are global.

New items are represented in KGTK format `node1/label/node2`.

We need to support two use cases:

**bulk (block) creation**: given a collection of strings, create new items for them. In addition to the strings, take the following arguments
  - prefix: a prefix string for naming the Q nodes, the name of the Q nodes will be Q<prefix>#######
  - class: the Q-node to use as P31 (optional)
  - description: a common description for all the items to be created

The bulk creation will be invoked using a block and creating items for all cells that are not wikified.

**single item creation**: ability to define a single item in an ad hoc fashion.

When new items are created, they are put in the KGTK file, as this file will be used in downstream tasks, that may be outside the control of T2WML, so we cannot assume that the only consumer is Datamart.

In addition, new items will be put in a wikifier file that T2WML uses. The idea is that when.users define new items for a block, then the whole block will be wikified.
