### ISSUE TITLE
updating a project file and then loading the project will not update the application, causing file not found and other errors

### ISSUE THREAD

**Issue by devowit** [usc-isi-i2/t2wml#231]
steps to replicate:

create a project, eg homicide, add files within a subdirectory, eg "t2wml".  lode the project in t2wml application.

rename the subdirectory. fix the project file to reflect the newly renamed subdirectory. load the project in t2wml application.

the project load will fail because it will still be trying to access the old, no longer existent sub-directory (and will overwrite the correct project file with a wrong one)

**Comment by saggu** [comment]
@devowit feel free to close this as you opened it yourself
