### ISSUE TITLE
send files to trash rather than deleting entirely

### ISSUE THREAD

**Issue by devowit** [usc-isi-i2/t2wml#232]
use package Send2Trash. check electron installer builds as expected

**Comment by zmbq** [comment]
Electron has `shell.moveItemToTrash` which may make this entire issue moot. Try it out.

**Comment by devowit** [comment]
should be added in 2.3.7, please close once tested

**Comment by saggu** [comment]
It is sending the folder to trash on deleting a project. I will close this issue.
