### ISSUE TITLE
Opening project settings from the UI takes longer with larger documents

### ISSUE THREAD

**Issue by g1eb** [usc-isi-i2/t2wml#237]
Seems like opening the settings is proportional to the source document, not sure if this is desired behavior.

I've timed the backend function and this one takes the longest:
[https://github.com/usc-isi-i2/t2wml/blob/development/backend/application.py#L422](https://github.com/usc-isi-i2/t2wml/blob/development/backend/application.py#L422)

Easy fix would be to not call the `project.update_settings(request.form)` function when users are making a `GET` request to open the form.

**Comment by zmbq** [comment]
We will read the settings in the frontend, bypassing the backend altogether.

**Comment by devowit** [comment]
(I think before reading from frontend, it's worth checking if the performance issues disappear in the current version.)

**Comment by devowit** [comment]
no longer relevant
