### ISSUE TITLE
Spinner does not stop after clicking on "Load to Datamart" button

### ISSUE THREAD

**Issue by saggu** [usc-isi-i2/t2wml#239]
**To Reproduce**
1. Run T2WML and Datamart-API
2. Upload the `04_worker_incidents.xlsx` file from the attached zip file
3. After yaml, wikifier etc files are automatically created, click `Load to Datamart`
4. The spinner in the table viewer keeps on spinning even after the user clicks on the alert. See the attached video in the archive.zip
[Archive.zip](https://github.com/usc-isi-i2/t2wml/files/5264996/Archive.zip)

**Desktop (please complete the following information):**
 - OS: mac
- branch: annotation-integration

**Comment by saggu** [comment]
Any updates on this issue please?

**Comment by devowit** [comment]
is this still happening?

**Comment by saggu** [comment]
This seems to be fixed in 2.4.1-Datamart
