### ISSUE TITLE
Ghost highlighted region

### ISSUE THREAD

**Issue by JiashengWu** [usc-isi-i2/t2wml#24]
After I applied a YAML file to one sheet, then I switched to another sheet and switched back, the highlighted regions disappeared, which was ok. But when I click some cells in the data region, the request of `/resolve_cell` still return something, which affects the table viewer and the output.

I suppose deleting the YAML file on backend whenever a `/upload_excel` request is fired would solve this issue.

![image](https://user-images.githubusercontent.com/28390143/61564260-eb078e00-aa2a-11e9-9dff-72490e3c38c2.png)

**Comment by bhatiadivij** [comment]
Fixed
