### ISSUE TITLE
Delete project crashes

### ISSUE THREAD

**Issue by dgarijo** [usc-isi-i2/t2wml#248]
**Describe the bug**
I created a project in my Documents folder (without subfolders). When I tried to delete it, T2WML crashed. I believe it's trying to delete other files from that folder which may be protected. This is potentially harmful.

**To Reproduce**
1. select as main folder a folder not created specifically for T2WML (Desktop, or Documents folder)
2. Click on delete project
3. T2WML warns you that all contents will be erased 
Program crashes.

**Expected behavior**
T2WML should delete only the project-related files. Also, what happens if I just want to remove a project from the list, but not from my computer?

**Comment by dgarijo** [comment]
Btw, when the folder was not in a folder like "My Documents", delete worked successfully

**Comment by saggu** [comment]
As per the discussion in the slack channel, we should only allow new projects to be created in empty folders.

**Comment by devowit** [comment]
as we no longer have the delete project option (only "open in file system" and  "remove from list" this issue is no longer relevant
