### ISSUE TITLE
load new project crashes frontend

### ISSUE THREAD

**Issue by devowit** [usc-isi-i2/t2wml#249]
**Describe the bug**
t2wml app shows empty screen 

**To Reproduce**
1. Load a project (any project from tutorials folder is fine)
2. Interact with project a bit
3. From menu bar, select new project, create new project
4. T2wml screen is now blank (no menu bar, nothing). Reloading project from project menu doesn't help.
If you reload the app from debug menu, and go to projects list, the new project is there, and when clicked on displays correctly, so it is being created properly in the backend.

**Expected behavior**
Should see an empty project view, ie empty tableviewer, 

**Screenshots**

**Desktop (please complete the following information):**
 - Windows 10
 - Executable version 2.3.7

**Additional context**
Creating new project from an empty project did not cause this problem

**Comment by saggu** [comment]
It is happening in Mac version as well

**Comment by zmbq** [comment]
The problem is that table-viewer.tsx sets up event handlers in wikistore.table. It sets them up in its constructor. The component should implement componentDidMount and hook into the event handlers there. It should unhook from the handlers in componentWillUnmount.

**Comment by devowit** [comment]
appears to have been fixed in the frontend redesign. reopen if recurs (or make new issue)
