### ISSUE TITLE
Questions for local development

### ISSUE THREAD

**Issue by g1eb** [usc-isi-i2/t2wml#253]
Some questions regarding the development process with t2wml:

First things first, `reload app` from the debug menu totally works but is missing a shortcut
(I was under the impression that cmd+R reloads the app, that's not the case right now - can we make that happen?)

Other questions:

Can we make the app open in full screen every time? (not a feature request for production but would be helpful to me in dev)
Can we have the app open dev tools/console by default every time? 

Can we open one of the projects by default (as to skip going through the list and clicking one on reload)
If this is something I can just change in the app for the time being, let me know (does not have to be a dev feature)

**Comment by dgarijo** [comment]
+1 to everything except making the app open dev tools console every time. That's a developer feature, not something that a user would like to see.

**Comment by szeke** [comment]
How about adding options in the settings menu to control:

- open in full screen mode: yes, no, last setting
- open in dev mode: yes, no, last setting
- open last project automatically: yes no

**Comment by zmbq** [comment]
t2wml now saves its last window state - position on the screen, size, maximized/not and the dev tools state. On startup it restores this state (in production it does not open the dev tools automatically, though). I don't think we need to bother the user with these settings, remembering the last window state is something that people expect, and I doubt they'll want to turn it off. Let's see if someone asks for it before we implement that.

As for opening the last open project - this is a little bit trickier to implement, as it requires moving code around from the renderer to the main process, or adding more interaction between the two. I'll leave that to Devora and Talya for next week, if you think it's necessary. I think that just like Word doesn't open the last project, t2wml doesn't have to, either.

**Comment by szeke** [comment]
I think this is a good compromise.

**Comment by g1eb** [comment]
Thanks for making the window size and position persistent on re-open!

These questions were mostly related to the development process (not really a feature request)
e.g. opening a project on load is to save me from clicking on one in the list view every time I reload the app :) 

I've added a quick ⌘⇧R shortcut to reload the app for development purposes, see https://github.com/usc-isi-i2/t2wml/pull/258

I think we can close this issue now
