### ISSUE TITLE
Error when switching projects

### ISSUE THREAD

**Issue by JiashengWu** [usc-isi-i2/t2wml#26]
After I'm done with a project (a pair of Excel file and Wikifier file), I want to open another project. The request of `/upload_excel` goes to an error if I open an Excel file first, since the previous Wikifier file may not applicative to the new Excel file.

It would also happens when I upload an inapplicable Wikifier file first and then the Excel file.

**Comment by JiashengWu** [comment]
I suppose there are 2 reasonable behaviors in such cases:
1. Try to apply the Wikifier file to the Excel file row-by-row, and just skip the inapplicable rows;
2. Unbind and delete the Wikifier file if there exists one or some rows that cannot apply to the Excel file, then just return the Excel data.

**Comment by bhatiadivij** [comment]
Fixed
