### ISSUE TITLE
Release a T2WML version for datamart

### ISSUE THREAD

**Issue by saggu** [usc-isi-i2/t2wml#263]
Datamart url = https://dsbox02.isi.edu:8888/datamart-api-wm

It requires a username, password in the url, I'll provide that separately

**Comment by devowit** [comment]
I don't understand what is being requested

**Comment by szeke** [comment]
The current release of T2WML does not include the Datamart extensions. Our clients want an installer for the version with the Datamart extensions.

**Comment by saggu** [comment]
I already did a release from a clone of master branch.

https://github.com/usc-isi-i2/t2wml/releases/tag/v2.3.8-datamart
