### ISSUE TITLE
No qualifier is shown in the output if the qualifier value is a constant

### ISSUE THREAD

**Issue by bhatiadivij** [usc-isi-i2/t2wml#27]
The output doesn't show the qualifier if the qualifier value is a constant. Refer the screenshot, the qualifier is returned in the `resolve_cell` request but is not shown in the GUI.

![image](https://user-images.githubusercontent.com/25511720/61573730-312f1280-aa68-11e9-97b0-ba3adf4cb530.png)

**Comment by JiashengWu** [comment]
Fixed.
