### ISSUE TITLE
CSV File is throwing an error while uploading to T2WML (see attached)

### ISSUE THREAD

**Issue by saggu** [usc-isi-i2/t2wml#271]
**Desktop (please complete the following information):**
 - Device: Mac
 - Version v2.3.8-datamart

[CHIRPSEthiopiaDailyPrecip_annotated.csv.zip](https://github.com/usc-isi-i2/t2wml/files/5484806/CHIRPSEthiopiaDailyPrecip_annotated.csv.zip)

**Comment by kyao** [comment]
The same problem on Windows and Linux. The error is: No columns to parse from file Cannot upload data file!

**Comment by devowit** [comment]
i was able to load this file fine in 2.3.9 on my windows machine, has the issue been resolved?

**Comment by devowit** [comment]
assuming no response for months means it's been dealt with, closing
