### ISSUE TITLE
Attached excel file does not work in T2WML v2.3.8-datamart on windows

### ISSUE THREAD

**Issue by saggu** [usc-isi-i2/t2wml#272]
When I uploaded this file in Mac, the datamart integration worked, but on windows it did not work.

[CHIRPSEthiopiaDailyPrecip_annotated.xlsx](https://github.com/usc-isi-i2/t2wml/files/5484831/CHIRPSEthiopiaDailyPrecip_annotated.xlsx)

@kyao could you please test this on windows

**Comment by kyao** [comment]
The file loads fine on Windows, but the date format is wrong. Deleting the format from yaml let the t2wml guest the format works.

**Comment by devowit** [comment]
so can this issue be closed, then?

**Comment by devowit** [comment]
assuming no response for months means it's been dealt with, closing
