### ISSUE TITLE
T2WML v2.3.9 adding files should be automatically sorted alphabetically (or whatever is the sorting order)

### ISSUE THREAD

**Issue by saggu** [usc-isi-i2/t2wml#277]
**To Reproduce**
1. upload file, 
2. file gets added at the bottom in the file tree list 
3. The file list is rearranged according to alphabetical order

**Expected behavior**
File should be added at the correct index when its uploaded

**Desktop (please complete the following information):**
 - OS :mac OS
 - Version v2.3.9

**Comment by talyashra** [comment]
Done in 'develepment', in 82373c9c6723fda5fbd61153d84102136c8dcf08 commit.

**Comment by talyashra** [comment]
Ready for testing

**Comment by devowit** [comment]
released in 2.3.10, close if tested ok
