### ISSUE TITLE
Fix incompatible changes for T2WML-Datamart Integration

### ISSUE THREAD

**Issue by saggu** [usc-isi-i2/t2wml#280]
**Describe the bug**
With the latest file tree, the integration with Datamart is no longer working.

https://github.com/usc-isi-i2/t2wml/blob/development/backend/application.py#L157

for example, there is no `tableData` in the `response` object anymore

![image](https://user-images.githubusercontent.com/6811931/98741872-42d5b100-2362-11eb-8e9d-56106800296d.png)

**To Reproduce**
1. set `annotation_integration` to `True` (https://github.com/usc-isi-i2/t2wml/blob/development/backend/application.py#L21)
2. Upload any file from the tutorial folder
3. See error in front end

**Comment by devowit** [comment]
fixed
