### ISSUE TITLE
Ease adding new properties

### ISSUE THREAD

**Issue by dgarijo** [usc-isi-i2/t2wml#290]
**Is your feature request related to a problem? Please describe.**
Related to issue #267. Adding properties is cumbersome in T2WML. If I want the property in a column to be recognized I have to: 
1- Declare it in the properties.tsv with a label and datatype (which most people are unfamiliar with)
2- Declare it in the wikifier so it can be properly recognized when parsing the data.
3- Pray that the label used matches exactly the label in the column, or it will not work. Sometimes if my property is something like PProduct, I have to rewrite it as Pproduct because the system messed up.

**Describe the solution you'd like**
I would like that T2WML helps me match a property to a wikidata property (issue #267); or if the property does not exist, allow me to add a new property from the UI. This could be done by clicking in the target column header, selecting "transform to property"; assigning it a PNode or a URI, and that's it.

**Comment by szeke** [comment]
Agreed. The current procedure is very cumbersome. We need an add property dialog to prompt for key information (this is relatively easy).

The more difficult decision is where to put the created properties, which will be in KGTK format. I suggest that T2WML allows the user to specify a "new properties" file, which is a name plus a path on disk. The project stores the name, and T2WML keeps the mapping of the name to a path on disk. This allows different users to have the file in different places on their local disk.  It is up to the user to share the new properties file with other users.

**Comment by devowit** [comment]
does wikify-mode plus auto-creation of properties/items for annotations sufficiently resolve this issue, or is there something additional that needs to be done?

**Comment by devowit** [comment]
addressed in lots and lots of sub-issues, so closing as a duplicate (of all of them together / the entirety of the 2.10 project board)
