### ISSUE TITLE
T2WML Tool name and acronym

### ISSUE THREAD

**Issue by dgarijo** [usc-isi-i2/t2wml#292]
Maybe I am nitpicking a little, but T2WML stands for Table to Wikidata Mapping Language. However this repository describes a tool that uses T2WML, not the language. Therefore, shouldn't this repository be renamed to:

- T2WMT: Table to Wikidata Mapping Tool or
- T2WMLT: Table to Wikidata Mapping Language Tool

I think it's important to have the 2 separated as different entities.

**Comment by devowit** [comment]
@szeke ?
