### ISSUE TITLE
Add version to T2WML executables in release

### ISSUE THREAD

**Issue by dgarijo** [usc-isi-i2/t2wml#294]
Right now every time I download a T2WML installer it has the name `t2wml-setup.exe`

The problem I have is that when I need to test multiple versions I always forget which version that installer corresponds to. It would help a lot to add the name of the version to the installer. For example `t2wml-setup-v2.4.0-Datamart.exe`

**Comment by zmbq** [comment]
New releases will have the version number as part of the installation file name.
