### ISSUE TITLE
Error when starting the application: Failed to execute t2wml server

### ISSUE THREAD

**Issue by dgarijo** [usc-isi-i2/t2wml#297]
**Describe the bug**
Once in a while, when starting the application, I will see the following error:
![image](https://user-images.githubusercontent.com/1520666/100940770-67c6cb00-34ad-11eb-9af0-b6c5e6bbf68f.png)

Restarting the application usually fixes the problem. 

**To Reproduce**
Open T2WML. I haven't been able to obtain this error consistently

**Screenshots**
See above

**Desktop (please complete the following information):**
 - OS: Windows 10 Pro
 - Version: v2.4.0-Datamart

**Smartphone (please complete the following information):**

**Additional context**

**Comment by devowit** [comment]
is this still happening?

**Comment by devowit** [comment]
I'm going to assume this isn't still happening, feel free to reopen if I'm mistaken
