### ISSUE TITLE
Cannot upload dataset to datamart

### ISSUE THREAD

**Issue by dgarijo** [usc-isi-i2/t2wml#298]
**Describe the bug**
I defined a project in v2.4.0 and then upgraded to v2.4.0-Datamart. When I click on "Load to Datamart", I get the following error:
![image](https://user-images.githubusercontent.com/1520666/100941088-e4f24000-34ad-11eb-9f4a-50b977e75e6e.png)

The dataset has an id, name, description and URL.

This error also appears in previous versions (tried v2.4.0 and v2.3.10-Datamart)

**To Reproduce**
1. Open a project
2. Click on 'Load to Datamart'
3. See error

**Expected behavior**
I would expect T2WML to register the dataset in Datamart.

**Screenshots**
![image](https://user-images.githubusercontent.com/1520666/100941173-0d7a3a00-34ae-11eb-80c4-609cc571b9a8.png)

**Desktop (please complete the following information):**
 - OS: Windows 10 Pro
 - Version: v2.4.0-Datamart

**Comment by saggu** [comment]
@dgarijo this happens when you delete a dataset after uploading an annotated spreadsheet to T2WML and before `Loading to Datamart`. 

Could you confirm this? We should add a check before `Loading to Datamart`, so that it creates the dataset if it can

**Comment by dgarijo** [comment]
Closing this issue. There are errors in the tutorials when uploading to datamart, but regular datasets seem to work
