### ISSUE TITLE
Datamart Integration: I have to press ⌘ R to display yaml file for an annotated spreadsheet

### ISSUE THREAD

**Issue by saggu** [usc-isi-i2/t2wml#300]
**Describe the bug**
Uploading a valid annotated spreadsheet, while Datamart Integration is ON, should display the yaml file after Datamart API returns successfully

**To Reproduce**
1. Open T2WML: 2.4.1-Datamart (https://github.com/usc-isi-i2/t2wml/releases/tag/v2.4.1-Datamart)
2. Create a new project
3. Upload this file - https://github.com/usc-isi-i2/t2wml/blob/development/tutorial/Region_Tutorial/region.xlsx
4. The file is wikified,
![image](https://user-images.githubusercontent.com/6811931/101065747-61d2f780-354a-11eb-9fa0-6a9abe0f52f0.png)
5. But the yaml section has not been filled in
6. Press ⌘ R (on mac) or refresh application, yaml appears
![image](https://user-images.githubusercontent.com/6811931/101065891-921a9600-354a-11eb-9ae5-674ee626394e.png)

**Expected behavior**
Yaml section should be filled without having to press  ⌘ R

**Desktop (please complete the following information):**
 - OS: MacOS
 - Version: 2.4.1-Datamart

**Comment by devowit** [comment]
should be fixed in 2.4.1
