### ISSUE TITLE
Switching between sheets of a multi sheet excel file, does not trigger Datamart Integration workflow

### ISSUE THREAD

**Issue by saggu** [usc-isi-i2/t2wml#301]
**Describe the bug**
Uploading an annotated excel file with multiple sheets, only triggers the Datamart Integration for the first sheet.

**To Reproduce**
1. Open T2WML: 2.4.1-Datamart (https://github.com/usc-isi-i2/t2wml/releases/tag/v2.4.1-Datamart)
2. Create a new project
3. Upload this file - https://github.com/usc-isi-i2/t2wml/blob/development/tutorial/Region_Tutorial/region.xlsx
4. The first sheet is wikified
5. Switch to any other sheet.
6. The Datamart Integration is not triggered

**Expected behavior**
I think T2WML should keep track of whether the datamart integration has been run for a sheet, and if not, datamart integration should trigger for a sheet the first time a sheet is selected.

This might be a new feature request

**Desktop (please complete the following information):**
 - OS: MacOS
 - Version: 2.4.1-Datamart

**Comment by devowit** [comment]
version 2.4.1
