### ISSUE TITLE
Add Datamart URL to be part of global settings, changeable from T2WML GUI

### ISSUE THREAD

**Issue by saggu** [usc-isi-i2/t2wml#302]
**Is your feature request related to a problem? Please describe.**
I would like to change the DATAMART API URL from GUI, without having to publish a new release

**Describe the solution you'd like**
Add another option in global settings for T2WML to change the DATAMART URL, another row in the following screen
![image](https://user-images.githubusercontent.com/6811931/101068932-34884880-354e-11eb-84be-17f5e436b9ad.png)

**Comment by g1eb** [comment]
We added this functionality on the `issue/303` branch in the `t2wml` repository, and the development branch in the `t2wml-api` repository (see commit https://github.com/usc-isi-i2/t2wml-api/commit/ca6fe694378574ec3131560dabe8135ffea223ff)

**Comment by devowit** [comment]
quick question re phrase "global settings".
the settings depicted are actually the per-project settings.
do you want the datamart endpoint to be per-project or across all projects by the same t2wml user? if so, it might make more sense to save them in .t2wml as a global setting.

**Comment by devowit** [comment]
is "datamart api url" the same as DATAMART_API_ENDPOINT used throughout the code? (in other words, do i need to replace DATAMART_API_ENDPOINT with calls to the new global settings?)

if not, what is it?

**Comment by devowit** [comment]
version 2.4.1

**Comment by g1eb** [comment]
> is "datamart api url" the same as DATAMART_API_ENDPOINT used throughout the code? (in other words, do i need to replace DATAMART_API_ENDPOINT with calls to the new global settings?)
> 
> if not, what is it?

I'm not sure if it's the same endpoint, but if it is we should definitely use the same variable :) 
@saggu do you know if this is the same thing?
