### ISSUE TITLE
Add the ability to Turn Datamart Integration On/OFF from T2WML GUI

### ISSUE THREAD

**Issue by saggu** [usc-isi-i2/t2wml#303]
**Is your feature request related to a problem? Please describe.**
Add an option in T2WML global settings screen to turn the Datamart Integration On/OFF

**Describe the solution you'd like**
Add a checkbox 

`Turn Datamart Integration ON`

![image](https://user-images.githubusercontent.com/6811931/101070040-aa40e400-354f-11eb-85eb-1a9d82e86a25.png)

If the checkbox is selected, An annotated spreadsheet will be sent to the Datamart Integration code.

**Comment by g1eb** [comment]
We added this functionality on the `issue/303` branch in the `t2wml` repository, and the development branch in the `t2wml-api` repository (see commit https://github.com/usc-isi-i2/t2wml-api/commit/ca6fe694378574ec3131560dabe8135ffea223ff)

**Comment by devowit** [comment]
version 2.4.1
