### ISSUE TITLE
Always run the steps listed in this Issue to test Datamart Integration before doing a release

### ISSUE THREAD

**Issue by saggu** [usc-isi-i2/t2wml#304]
**DO NOT CLOSE THIS ISSUE, please**

This issue is a placeholder to run the integration test for Datamart for anyone publishing a new release. 

Steps:

1. Turn on Datamart Integration (described in #303 )

2. Upload this file, https://github.com/usc-isi-i2/t2wml/blob/development/tutorial/Region_Tutorial/region.xlsx

3. Confirm T2WML looks like this .

![image](https://user-images.githubusercontent.com/6811931/101070618-6c908b00-3550-11eb-9cab-2b8e6b44eefa.png)

4. Click `Load to Datamart`, confirm success

5. Upload this file, https://github.com/usc-isi-i2/t2wml/blob/development/tutorial/Time_Qualifier_Tutorial/qualifier.xlsx

6. Confirm T2WML looks like this ,

![image](https://user-images.githubusercontent.com/6811931/101070804-aeb9cc80-3550-11eb-9c0f-9e2dc3913f14.png)

7. Click `Load to Datamart`, confirm success

8. Upload this file https://github.com/usc-isi-i2/t2wml/blob/development/backend/tests/files_for_tests/04_worker_incidents.xlsx

9. Confirm T2WML looks like this, 

![image](https://user-images.githubusercontent.com/6811931/101071396-6949cf00-3551-11eb-95f4-533804e6f840.png)

10. Click `Load to Datamart, confirm success`

11. run this command, from a terminal,
```
curl -XDELETE "https://datamart:datamart-api-789@dsbox02.isi.edu:8888/datamart-api-wm/metadata/datasets/tutorial_dataset?force=true"
```

Replace the Datamart URL as required.

**Comment by devowit** [comment]
version 2.4.1 onwards

**Comment by devowit** [comment]
this issue has been converted into an automated test and is now being closed

**Comment by devowit** [comment]
steps 1-6 have been automated/added to testing suite. I'm not sure I automated the subsequent steps, I will have to check.

**Comment by saggu** [comment]
@devowit is this automated now ?

**Comment by devowit** [comment]
given all the changes to datamart etc, is this issue still relevant?

**Comment by devowit** [comment]
closed because no longer relevant
