### ISSUE TITLE
After uploading dataset, result is not clickable and URL is not completely shown

### ISSUE THREAD

**Issue by dgarijo** [usc-isi-i2/t2wml#305]
**Describe the bug**
I was able to upload a dataset to Datamart with T2WML. However, the result is shown as follows:
![image](https://user-images.githubusercontent.com/1520666/101090989-5bee0e00-356c-11eb-855a-5f82c0196c5a.png)

Which makes it impossible to click on the dataset or copy its URL. Naturally, that's the first thing users want to do to make sure everything was uploaded correctly.

**To Reproduce**
Upload a dataset to datamart.

**Expected behavior**
I should be able to copy the URL of the dataset

**Screenshots**
![image](https://user-images.githubusercontent.com/1520666/101091083-86d86200-356c-11eb-83f3-f02dbb595330.png)

**Desktop (please complete the following information):**
 - OS: Windows 10 Pro
 - Version: 2.4.0-Datamart

**Smartphone (please complete the following information):**

**Additional context**

**Comment by devowit** [comment]
i think this is connected to #191 , @saggu ?

**Comment by saggu** [comment]
@devowit Daniel wants the ability to copy the url, it is related to #191
