### ISSUE TITLE
add t2wml to path in mac, windows, and linux

### ISSUE THREAD

**Issue by devowit** [usc-isi-i2/t2wml#309]

**Comment by zmbq** [comment]
On Windows - add t2wml to user path (HKEY_CURRENT_USER\Environment\Path) You can use windows-registry from npm.

On Linux, add a link to $HOME/.local/bin: ln -s  <electron executable> $/HOME/.local/bin/t2wml .
Create $HOME/.local/bin if it does not exist.
If $HOME/.local/bin is not in the path, ask the user to add it to their PATH.

On Mac, use oascript to add t2wml to the path:

`osascript -e "do shell script \\"mkdir -p /usr/local/bin && ln -sf \''+ <electron executable>+'\' \''+target+'\'\\" with administrator privileges"`
(taken from here: vscode/cli.contribution.ts at aede2434b07a6f84ca42b94323927f415967f8cd · microsoft/vscode (github.com))

**Comment by zmbq** [comment]
@saggu  can you please test this on your Mac?

**Comment by devowit** [comment]
@saggu  just to be clear, what itay wants you to test is the button help/Add T2WML to PATH, not the manual instructions he describes above. check if the button works to add to path so that typing `t2wml` in command prompt opens the program (and typing `t2wml path/to/file` opens the project

**Comment by saggu** [comment]
So, I added t2wml to path using `help/add t2wml to your path`

1. typing t2wml in terminal opens the application :white_check_mark:

2. typing `t2wml path/to/folder` opens the project in that folder, or so I thought :x:

![image](https://user-images.githubusercontent.com/6811931/107271042-89d64f80-6a00-11eb-81b7-ed0d13a41a07.png)

See the paths, now I have 2 projects instead.

3. typing `t2wml path/which/does/not/exist` opens T2WML at the `Projects` screen :interrobang:
I think this is the correct behavior, but maybe notify the user that this folder does not exist

4. typing `t2wml path/to/a/blank/folder` open the `New Project` folder :white_check_mark:

@devowit @zmbq

**Comment by saggu** [comment]
Adding more information for point # `3` above, 

Uploading a file to one project will show up in the second project as well. Just have to pick a better way to display `paths`

**Comment by saggu** [comment]
One more thing,

![image](https://user-images.githubusercontent.com/6811931/107299060-78566d00-6a2b-11eb-846a-ac8a268cef20.png)


the `t2wml` command should exit after opening the application, it currently hangs in the terminal and only exits after T2WML is closed

**Comment by devowit** [comment]
>typing t2wml path/to/folder opens the project in that folder, or so I thought

it would help me understand better if I understood your directory structure. the paths are relative to the current folder you're in, so in folder /home if you did t2wml /mypath it would try to open a project in /home/mypath, not in /mypath. is that what you're seeing happen?

as for the bug where "Uploading a file to one project will show up in the second project as well", that's much more worrisome, that's what happening n the home/mypath case or in other cases as well?

>I think this is the correct behavior, but maybe notify the user that this folder does not exist

I think it might be logged in the console, I guess we could add a visible alert.

**Comment by saggu** [comment]
> it would help me understand better if I understood your directory structure. the paths are relative to the current folder you're in, so in folder /home if you did t2wml /mypath it would try to open a project in /home/mypath, not in /mypath. is that what you're seeing happen?

I think these are symbolic links, not that severe but confusing for users. Both links point to the same folder, not sure if this issue can be resolved (following symbolic links) in electron. I saw that as I was using `/tmp` folder for projects,  maybe others will never see it. Table this for now.

>as for the bug where "Uploading a file to one project will show up in the second project as well", that's much more worrisome, that's what happening n the home/mypath case or in other cases as well?

Again, only happens in the above case (symbolic links) which are essentially the same folder

**Comment by devowit** [comment]
ok, got it. thanks.

**Comment by zmbq** [comment]
We can probably follow symbolic links and see that they point to the same directory, but this may lead to a huge potential mess, as it's possible the *permissions* are not the same, depending on the path you followed, which may include numerous links. I think that it's reasonable that if you refer to the project with two names, you will see it twice.

As for holding up the shell, this is a Mac only feature, on Windows it does work. I've pushed a fix to development that should solve this. At some point we should remove all the printouts, or at least make them optional.
