### ISSUE TITLE
Datamart api url from settings is getting removed in case of errors ?

### ISSUE THREAD

**Issue by saggu** [usc-isi-i2/t2wml#315]
**To Reproduce**
1. Open Project settings by pressing ⌘,
2. Check `Turn Datamart Integration ON` checkbox
3. Set URL in `Datamart api url` to http://www.google.com
4. Upload the attached spreadsheet
5. Nothing will happen because the url is invalid
6. Reload app Shift + Command + R in MAC
![image](https://user-images.githubusercontent.com/6811931/101814678-5136fa00-3ad3-11eb-9cf5-cd70d920d2ad.png)

7. Open the settings again, confirm the URL in `Datamart api url` is gone
8. Do this a couple of times, the T2WML completely freezes

**Desktop (please complete the following information):**
 - OS: MacOS
 - Version 2.4.1
[04_worker_incidents.xlsx.zip](https://github.com/usc-isi-i2/t2wml/files/5674922/04_worker_incidents.xlsx.zip)

**Comment by devowit** [comment]
this doesn't seem to be related to errors at all. after a bunch of efforts debugging this it seems to be some kind of race condition where sometimes but not always the settings are initialized blank instead of taken from the saved settings somehow -- so you need to leave the project or reload the app so that it accesses saved settings to replicate). I am still working on tracking down and fixing whatever is causing the race condition.

I was not able to replicate the bit where the app froze.

**Comment by devowit** [comment]
Has this issue ever occurred without having reloaded the app? (Reloading the app is something for debugging/development mode and it can leave React in an inconsistent state, it shouldn't be used by regular users...)(this connects in general with the need to have a console separate from the developers console that we can move messages for regular users to/ replacing all such messages with some other, more suitable form of communication like a better error display when clicking on an errored cell)

**Comment by devowit** [comment]
@saggu does this still need to be addressed? does it happen when refeshing the page from project menu or only when reloading from debug menu?

**Comment by saggu** [comment]
I see this setting is now moved to Global settings. A couple of observations.

1. No hot key for `Global Settings`
2. T2WML shoul not allow me to `save` if I turned the Datamart Integration `ON` without specifying a url

**Comment by devowit** [comment]
do you have a preference for hot key?

**Comment by szeke** [comment]
I don't care much about the hot key as users don't go to setting often. We should make sure that return works to submit the popups, and that TAB works to switch fields.

**Comment by devowit** [comment]
opening a separate issue (#376) for the pop-up enhancements since this is not related to the bug this issue was opened to address.

@saggu at this point the bug is still happening or isn't? if it isn;t we can close this.

**Comment by saggu** [comment]
@devowit `T2WML should not allow me to save if I turned the Datamart Integration ON without specifying a url` is still an issue

**Comment by devowit** [comment]
It's not related to this issue (url getting removed in case of errors) , I
moved it to its own issue. Is the original issue still relevant?
