### ISSUE TITLE
Standardize structure of the error messages

### ISSUE THREAD

**Issue by g1eb** [usc-isi-i2/t2wml#335]
We added the error messages (minor/major) to the popup menu in the output mode.

The issue is that sometimes the errors pertain to a property and sometimes to qualifier, and sometimes to property of the qualifiers. In effect the resulting error object looks something like this: 

```
{
    "property": "Could not get property type for Q7649586",
    "qualifier": {
        "0": {
            "property": "Missing property "
        }
    }
}
```

For display purposes this is very tricky as I'm not sure how many levels deep to look for the actual error messages to display.

Would it be okay to return a flat list of all the errors that we have on each individual cell?
Bonus feature, include the error type, i.e. `minorError` or `majorError`. For example:

```
[{
    "error": "Could not get property type for Q7649586",
    "type": "majorError",
    "role": "property",
}, {
    "error": "Missing property ",
    "type": "majorError",
    "role": "qualifier",
}, {
    .........
    ............ other errors if any
    ...............
}]
```

**Comment by devowit** [comment]
yes this should be easily doable. 

(we've had another long-standing request to change error messages, #135,  which was constantly being pushed off (and which was less easily doable...) I don't know to what extent that request still applies especially as we move away from yaml-centric use-cases... in any case @saggu if you want to use this issue to talk about any requests for error messages?)

**Comment by devowit** [comment]
in terms of the role field: how do you want me to distinguish between a property/unit etc of a qualifier vs of the main statement? (one option is I can have a boolean flag for qualifier, another is that we have roles unit/property and then qualifier-unit, qualifier-property...)

**Comment by devowit** [comment]
the role field, is meant to just be annotation roles? because we also have keys like calendar, precision etc. in th ecurrent system that's the key, "calendar", is there something you want it to be instead?

**Comment by devowit** [comment]
we could have extra fields like calendar all be on "value", which will either be main value or qualifier value depending on the qualifier flag?

**Comment by g1eb** [comment]
I think in terms of presentation of the errors we just want to show the error message and the field it pertains to, plus maybe the type of error (minor/major) to use a different color. I think the examples you posted on slack are great!

A snippet of that for reference:
```
        "F7": [
            {
                "role": "qualifier",
                "message": "Invalid datetime: Bad date time",
                "qualifier_index": 0,
                "level": "Minor",
                "field": "value"
            },
            {
                "role": "qualifier",
                "message": "Failed to resolve for value (=item[C, $row])",
                "qualifier_index": 1,
                "level": "Minor",
                "field": "value"
            }
        ],
```
