### ISSUE TITLE
qualifier fields disappearing

### ISSUE THREAD

**Issue by devowit** [usc-isi-i2/t2wml#337]
marked a qualifier, type string, gave it hardcoded property.
realized i'd given it the wrong property
when i clicked it, it didn;t have any fields in pop up window except role selection.
clicked it again, for role qualifier, type quantity (instead of string)
clicked back to type string, added fixed property
...annotation for that qualifier block disappeared entirely
had to revuild it again and then things worked

**Comment by g1eb** [comment]
this is fixed in development branch
