### ISSUE TITLE
annotation menu will refuse to go away

### ISSUE THREAD

**Issue by devowit** [usc-isi-i2/t2wml#340]
this appears to be an issue catching mousedown or something?

in any case, i occasionally cannot get the annotation menu to go away. without actually clicking on any cell it pops up over and over in a loop, and keeps selecting these rectangles as if was clicking...

**Comment by zmbq** [comment]
Look at Elemenet.setCapture, or a way to capture the mouse in electron.

**Comment by g1eb** [comment]
According to [MDN](https://developer.mozilla.org/en-US/docs/Web/API/Element/setCapture), `Element.setCapture()` is non-standard and is not supported by major browsers

Fixed by binding the `mouseUp` event handler to the document rather than the table component.
