### ISSUE TITLE
Change all the `| null`s in type defintions to `| undefined`

### ISSUE THREAD

**Issue by zmbq** [usc-isi-i2/t2wml#346]
There are may types with properties that are defined as `prop: string | null`. Unless there's a compelling reason, this should change to `prop?: string` or `prop: string | undefined`

**Comment by ChanaChelem** [comment]
type-script-fix  commits:
fd8746bf17e674f1b3aaebf38550e830136506b0
178982991140db54be50f16ba89c89d73adffbab
a35001bd4009667ddb7f2676c61d25cccab698de
 1afbadc26602f13ea9f18ca3fa5f926ee43ddf39
