### ISSUE TITLE
Allow selecting multiple cells for wikification

### ISSUE THREAD

**Issue by devowit** [usc-isi-i2/t2wml#363]
in the backend, all wikification will be saved cell-by-cell. but the frontend will allow users to select multiple cells and apply the same wikification to all of them.

**Comment by devowit** [comment]
We can have the frontend just send back a list of cells and the QNode they should be wikified to, the backend can take care of going over it in a loop.

**Comment by devowit** [comment]
@szeke is this still needed, or are we sticking to per-block wikification and that's it?

**Comment by devowit** [comment]
alternately. is this a duplicate of #381?

**Comment by szeke** [comment]
We don’t need this, we are doing per-block wikification
