### ISSUE TITLE
Filetree Tooltip is wrong

### ISSUE THREAD

**Issue by zmbq** [usc-isi-i2/t2wml#369]
Hovering over any node in the file tree shows a tooltip containing the datafile's name. It should contain the entire content of the node currently being hovered instead.

**Comment by g1eb** [comment]
> It should contain the entire content of the node currently being hovered instead.

Do you mean we should put the relative path to the file in the tooltip? What is the "entire content"?

**Comment by devowit** [comment]
yes, the relative path to the content (or, for sheet name, the sheet name). whatever text the node actually contains...

@zmbq  once we've got hover working, should we be truncating file strings to end in ... rather than having a scrollbar at the bottom? looking at VS Code as an example...
