### ISSUE TITLE
Add a search feature for properties and units in annotation mode

### ISSUE THREAD

**Issue by g1eb** [usc-isi-i2/t2wml#372]
use the kgtk search api to search for properties in the annotation menu, similar to the wikify mode (WIP)

- [x] properties
- [x] units

**Comment by g1eb** [comment]
Adding qnode search for the unit input field as well (q-nodes that are instance of Q47574)

@szeke does the qnode annotation need the property input field?
![image](https://user-images.githubusercontent.com/1916056/110379964-57723f00-800c-11eb-9a54-8454f7e0b1f6.png)

**Comment by g1eb** [comment]
Also there is an option to select `unit` as a role for the annotation block, do we want to add a search for units in that menu too?

![Screen Shot 2021-03-08 at 1 03 44 PM](https://user-images.githubusercontent.com/1916056/110381820-dec0b200-800e-11eb-8bab-36edc8886932.png)

**Comment by g1eb** [comment]
Both property and unit search is in the development branch now

**Comment by devowit** [comment]
it needs to also be possible to annotate properties in wikify mode, not just from annotation menu. is that a separate issue?

both unit and property search working fine for me.
