### ISSUE TITLE
Add support for specifying P31 restrictions on qnode query in wikify-mode

### ISSUE THREAD

**Issue by devowit** [usc-isi-i2/t2wml#375]
When the user is searching for a property/item to wikify to, the search engine interface (both the frontend and the service) should allow the user to specify P31 (instance of) restrictions, eg if the user specifies P5 then results will be limited to wikidata items that are instances of "human". The P31 input needs to also be a search box, ie the user could search for "human" and get P5 as a suggestion and then use that to help them narrow down their search results for "George Washington"

**Comment by devowit** [comment]
@szeke  have i described accurately how this is supposed to work?

**Comment by szeke** [comment]
Constraining by instance-of is only relevant for item wikification, but not for property wikification

**Comment by saggu** [comment]
Already supported in the backed search API
