### ISSUE TITLE
[Mac] installer icon for t2wml can't be found after installing

### ISSUE THREAD

**Issue by devowit** [usc-isi-i2/t2wml#391]
(reported by gleb)

**Comment by devowit** [comment]
@zmbq is this related to the issue you experienced, as well?

**Comment by devowit** [comment]
It gets installed where it was last compiled. if you delete the app file in electron/out and then install from the installer the problem should disappear. let me know if this works. @g1eb

**Comment by g1eb** [comment]
Can confirm, after deleting `electron/out` folder and installing from `.pkg` the icon did appear in the launcher, closing.
