### ISSUE TITLE
fixing range of an annotation block does not update

### ISSUE THREAD

**Issue by devowit** [usc-isi-i2/t2wml#392]
if i select a block D9:D43, and submit that annotation-- and then realize I made a mistake and actually I want to submit D9:D42, and i change tht in the range textbox-- when i resubmit the block, nothing changes.

in the backend, I'm still being sent the same x1, y1, x2, y2 coordinates as before the change, so this appears to be an error in the frontend.

resizing with dragging the bottom corner does work, though.

**Comment by g1eb** [comment]
This should be fixed in the development branch now
