### ISSUE TITLE
Allow users to remove wikified qnodes

### ISSUE THREAD

**Issue by g1eb** [usc-isi-i2/t2wml#395]
Right now there is no way to remove wikification from a particular cell, we should probably allow users to remove wikifications.

**Comment by g1eb** [comment]
@devowit could you take a look at this `remove_qnode` endpoint I just added? It takes in the same parameters as the `set_qnode` function but should work in reverse, removing relevant lines from the `user-input-wikification.csv`. 

You can find this `remove_qnode` function here (`feature/remove-wikification` branch):
https://github.com/usc-isi-i2/t2wml/blob/feature/remove-wikification/backend/application.py#L623

**Comment by g1eb** [comment]
Sorry if that was confusing! Let me clarify, currently there are two exact same functions `set_qnode` and `remove_qnode` - they get the same parameters (qnode id, selection area, etc).

What I was meaning to ask you is to take a look at the `remove_qnode` and make it undo what the previous `set_qnode` function did in terms of writing to that `user-input-wikification.csv` file. I can take a stab at it but thought you might have a better idea on how to do it correctly right off the bat.

**Comment by devowit** [comment]
pushed in branch version/2.8.0
