### ISSUE TITLE
show block edges in wikify mode as well

### ISSUE THREAD

**Issue by devowit** [usc-isi-i2/t2wml#400]
borders so when users select apply to block they know what its applying to

**Comment by g1eb** [comment]
this is in the `version/2.8.0` branch now

**Comment by devowit** [comment]
i don't see this working on my computer

**Comment by g1eb** [comment]
strange, this is with `applyToBlock=true` in the wikify menu, right?

**Comment by devowit** [comment]
nevermind, i expected it to work differently, it works fine.
