### ISSUE TITLE
Output window does not show dates in the correct precision

### ISSUE THREAD

**Issue by szeke** [usc-isi-i2/t2wml#402]
In the Nobel laureates example, the precision is year. The output should show the year only

**Comment by devowit** [comment]
is this just for display, or also for the data we are uploading/downloading/etc? ie am i making a change in the frontend display, or in the actual data returned by the backend and passed along everywhere?

**Comment by devowit** [comment]
from meeting: @szeke said it's just fixing display in output window

**Comment by devowit** [comment]
@szeke  please discuss how you would like dates formatted in the output display.

precision year: I assume you want YYYY
what about precisions month, day, etc?

do you want MM/YYYY, DD/MM/YYYY, DD/MM/YYYY HH:MM:SS formats? something else?


what about decade/century/etc precision? how do you want those handled?

**Comment by szeke** [comment]
year: YYYY
day: March 31, 2017
finer: using ISO format YYYY-MM-DD HH:MM:SS depending on precision
century: 20th century
millenium: 2nd millenium, coarser handled similarly

**Comment by devowit** [comment]
our precision mapping supports:
        "gigayears": 0,
        "100 megayears": 1,
        "10 megayears": 2,
        "megayears": 3,
        "100 kiloyears": 4,
        "10 kiloyears": 5,
        "millennium": 6,
        "century": 7,
        "10 years": 8,
        "years": 9,
        "months": 10,
        "days": 11,
        "hours": 12,
        "minutes": 13,
        "seconds": 14

should i just not bother with everything above millenium? or when you say coarser handled similarly do you mean I output "1st 100 kiloyears, 2nd 100 kiloyears" etc.

for hours, I'd output `YYYY-MM-DD HH`?
