### ISSUE TITLE
Quantity qualifiers have junk in the output window

### ISSUE THREAD

**Issue by szeke** [usc-isi-i2/t2wml#403]
![2021-03-18_10-40-50](https://user-images.githubusercontent.com/1074599/111671862-95bee980-87d6-11eb-97ed-a8c7eb129eb0.png)
 The output window shows ([object Object])

[elections.zip](https://github.com/usc-isi-i2/t2wml/files/6166208/elections.zip)

**Comment by devowit** [comment]
this was fixed in the process of fixing #409
