### ISSUE TITLE
Load to Datamart failing from application release 2.8.0

### ISSUE THREAD

**Issue by kyao** [usc-isi-i2/t2wml#407]
When clicking on the `Load to Datamart (beta)` button, I get error pop up window with message:

![image](https://user-images.githubusercontent.com/1087657/112096748-1cb7ed00-8b5c-11eb-8198-c8d17fa76ceb.png)

On the datamart side, I see a 404 error. T2wml is trying to a post command without first defining the dataset.

```
POST /dataset/poverty_rate_v3/t2wml
```

Here is the project zip file:

[dp-poverty-3.zip](https://github.com/usc-isi-i2/t2wml/files/6187017/dp-poverty-3.zip)

**Comment by kyao** [comment]
After the above post failed, I create a new project then tried to `Upload data file`. It fails with this message:
![image](https://user-images.githubusercontent.com/1087657/112097417-33ab0f00-8b5d-11eb-8b2c-c764e6b863fe.png)

If I reload the application and open the project, I find that the CSV data file is already loaded.

**Comment by kyao** [comment]
With the new merge in the `development` branch. The dataset is being defined in the Datamart. But there no variables in the dataset.

**Comment by kyao** [comment]
> After the above post failed, I create a new project then tried to `Upload data file`. It fails with this message:
> 
> If I reload the application and open the project, I find that the CSV data file is already loaded.

This `Upload data file` bug is unrelated to the datamart upload failing. It occurs even when I do not attempt to upload to datamart.

**Comment by devowit** [comment]
a series of fixes in t2wml, t2wml-api, and datamart seem to have fixed this bug.

**Comment by devowit** [comment]
@kyao  can you create a separate issue for the upload data file bug and include the steps taken and the file? have not had an issue uploading data files thus far...
