### ISSUE TITLE
Create property type

### ISSUE THREAD

**Issue by kyao** [usc-isi-i2/t2wml#408]
T2WML automatically creates property pnodes, but not their data types.
Is there a way to define property data types? Or, perhaps T2WML should define the property type based on the type of the dependent variable annotation region.

![image](https://user-images.githubusercontent.com/1087657/112099702-3871c200-8b61-11eb-8a34-799f62658fe9.png)

Here is the project zip file:
[AMIS-2.zip](https://github.com/usc-isi-i2/t2wml/files/6187193/AMIS-2.zip)

**Comment by szeke** [comment]
This is the project we want to create for poverty

<img width="1669" alt="image" src="https://user-images.githubusercontent.com/1074599/112238703-678c4000-8c02-11eb-91f4-71c4e4effa57.png">

<img width="1669" alt="image" src="https://user-images.githubusercontent.com/1074599/112238722-6ce98a80-8c02-11eb-8123-7d4a90a0d6d1.png">

[poverty.zip](https://github.com/usc-isi-i2/t2wml/files/6193630/poverty.zip)

**Comment by devowit** [comment]
fixed in usc-isi-i2/t2wml-api/commit/97ffe42f8a401be8cca43e8ab7fc8b5fc71eaa12
