### ISSUE TITLE
add support for PgUp/PgDn buttons to navigate spreadsheet

### ISSUE THREAD

**Issue by devowit** [usc-isi-i2/t2wml#411]
especially in the middle of annotating

**Comment by g1eb** [comment]
I was just testing the table navigation with arrow keys and it seems like we already support page up and page down keys.
It's possible this came over with the switch to the virtualized table layout.

**Comment by devowit** [comment]
I just tried this on the site at t2wml.isi.edu and it doesn't work, what actions did you take where it worked?

**Comment by g1eb** [comment]
For the output preview you can click anywhere in the table, then use arrow keys or pageUp/pageDown to navigate.
For the input table you can click on the index column, or create annotation and close the menu, then try the pageUp/pageDown navigation.

The thing is that the table element where we can scroll needs to be "focused" or be the last element that was "focused", we could probably do a better job at focusing it programmatically though.

**Comment by devowit** [comment]
cool 👍
