### ISSUE TITLE
Error when creating a new project because `~/.t2wml` directory does not exist

### ISSUE THREAD

**Issue by g1eb** [usc-isi-i2/t2wml#420]
Sometimes we need to remove the `~/.t2wml` directory to fix issues, and this directory should be recreated when t2wml starts, is that correct? We noticed some errors about `~/.t2wml/gui-settings.json` file missing and/or the `~/.t2wml/cache` directory missing, see the attached screenshot.

![Screen Shot 2021-03-23 at 6 28 20 PM](https://user-images.githubusercontent.com/1916056/112246857-90b3cd00-8c10-11eb-8486-bf1478e8f2c7.png)

![Screen Shot 2021-03-23 at 6 28 59 PM](https://user-images.githubusercontent.com/1916056/112246882-9a3d3500-8c10-11eb-9530-d31597503051.png)

**Comment by devowit** [comment]
fixed in usc-isi-i2/t2wml-api@7a320e5f4570459d6877ed6b6e09508ff33e299a and de1b91613f669c81754267efed0057f6a2d494f2
