### ISSUE TITLE
annotations double after changes

### ISSUE THREAD

**Issue by devowit** [usc-isi-i2/t2wml#424]
if i create a dependent variable annotation with a property
then go back and edit the annotation to remove the property
or i change the type from string to quantity
or other such changes

instead of changing the annotation block, a new one is created.

I end up having to delete the annotation multiple times and then recreate it from scratch to "Edit" it instead of being able to edit it.

**Comment by devowit** [comment]
I have gotten this bug multiple times but cannot consistently replicate it

**Comment by ChanaChelem** [comment]
I cannot replicate it
