### ISSUE TITLE
resizing annotations via the range field (in the menu)- crash

### ISSUE THREAD

**Issue by ChanaChelem** [usc-isi-i2/t2wml#435]
**Describe the bug**
resizing annotations via the range field (in the menu)- everything crashing

**To Reproduce**
1. Select an area for annotate.
2. Cange the value of "selected area".
3. See error.

**Screenshots**
![image](https://user-images.githubusercontent.com/55047726/115198497-c908d700-a0fa-11eb-9e89-d38b74743d3f.png)

**Comment by devowit** [comment]
another problem:
if i have a range like D5:E13
and I want to change it to D5:E12
as soon as I backspace the 3, to start typing 2, the selected area suddenly resets to "D1:F5". If i try again, erasing the 5 to start typing, say, 20, it forcibly exits the text box and i can't keep typing

**Comment by ChanaChelem** [comment]
branch selection-area-menu
commit 20174320876a379176d772a7306416600a2ea608
