### ISSUE TITLE
Integration of pathlib in older versions of Python

### ISSUE THREAD

**Issue by iAmeeth** [usc-isi-i2/t2wml#45]
I am working on a system with Python version 3.5.5. I keep on getting the error TypeError: invalid file: WindowsPath("/somepath")

pathlib integrates seemlessly with "open" only in Python 3.6 and later 

> The built-in open() function has been updated to accept os.PathLike objects, as have all relevant functions in the os and os.path modules, and most other functions and classes in the standard library.

A standard fix for this would be to convert the object to a string before opening the files.

**Comment by bhatiadivij** [comment]
@iAmeeth T2WML won't work with any python version below version 3.6. 
T2WML uses ETK which has a requirement of Python3.6+to work. 
Refer: https://github.com/usc-isi-i2/etk#installation
