### ISSUE TITLE
v2.10.0-pre.1 does not load

### ISSUE THREAD

**Issue by g1eb** [usc-isi-i2/t2wml#468]
We were trying out the new pre-release and it does not load on a mac (we tried multiple versions).
It's hanging while waiting for the backend to load and disappears after ~1 minute.
Attached is the screenshot of what it looks like.

![Screen Shot 2021-06-11 at 10 46 33 PM](https://user-images.githubusercontent.com/1916056/121766571-b2359e00-cb07-11eb-91ad-0336f968ca01.png)

**Comment by devowit** [comment]
yes the new pre-release is totally broken i thought we said that in the meeting. don't use it. my demo during the meeting wasn't from the pre-release.

**Comment by g1eb** [comment]
okay, thanks for the clarification we can close this
