### ISSUE TITLE
Issues with loading the partial output CSV

### ISSUE THREAD

**Issue by g1eb** [usc-isi-i2/t2wml#469]
The response from the `/api/partialcsv` endpoint is now always this empty :

```
{"partialCsv":{"cells":[["subject","property","value"]],"dims":[1,3],"firstRowIndex":0}}
```

This is happening on the `feature/wikifier_endpoints` branch.

I'm unsure if this is related to the branch being out of sync with `development` branch of `t2wml-api` - which is possible.
Could this `feature/wikifier_endpoints` branch be merged in to the main development branch of t2wml?

**Comment by devowit** [comment]
can you attach the project where this is happening?

**Comment by g1eb** [comment]
I'm using this file right here 
[annotation_example.xlsx](https://github.com/usc-isi-i2/t2wml/files/6645850/annotation_example.xlsx)

I'll rebuild the project using the latest on the development branches and try again to confirm

**Comment by g1eb** [comment]
this totally works now! closing this issue
