### ISSUE TITLE
Can we add layers to the suggested/guessed annotation blocks response

### ISSUE THREAD

**Issue by g1eb** [usc-isi-i2/t2wml#471]
Every other response object has the layers object containing the qnodes that have been wikified.

The suggested annotation blocks request to `/api/annotation/guess-blocks` is the exception, would it be possible to add the layers to that response as well?

**Comment by g1eb** [comment]
To clarify, we need qnode layer in order to highlight the wikified wikidata items and properties in the table.

**Comment by devowit** [comment]
i guess we could but that definitely seems like the wrong place to put it...  why are you not getting the qnodes from the requests that would be responsible for creating the qnodes?

**Comment by g1eb** [comment]
I think you are referring to the `/api/auto_wikinodes` endpoint is that correct? I was not sure if the wikification happens automatically when we create the annotations or if I had to call the auto_wikinodes endpoint separately.
