### ISSUE TITLE
Suggested blocks should have the full property node if possible

### ISSUE THREAD

**Issue by g1eb** [usc-isi-i2/t2wml#472]
Right now we only get the `property: "P585"` back for the property when calling the `/api/annotation/guess-blocks` endpoint.

It would be nice if it could contain the entire property, much like the endpoint over at `/api/annotation/suggest` does, e.g.:

```
{
  data_type: "time"
  description: "time and date something took place, existed or a statement was true"
  id: "P585"
  label: "point in time"
}
```

**Comment by devowit** [comment]
should be fixed with latest t2wml-api from development and latest t2wml development

**Comment by g1eb** [comment]
thank you! I'll check it out on the development branch(es)

**Comment by g1eb** [comment]
done and done, closing
