### ISSUE TITLE
Web GUI "Save to File"

### ISSUE THREAD

**Issue by kyao** [usc-isi-i2/t2wml#476]
The Web GUI should have a Save to File button. The result file returns is a zip file.  

The name of the zip is: `<project name>`-`<stem of  the uploaded csv filename>`.zip

The content of the zip is:
+ canonical.csv
+ dataset-metadata.json
+ variable-metadata.json
+ annotation.json

The canonical.csv is the canonicalized CSV file generated by T2WML.

The dataset-metadata.json contains:
```
{
    "name": <name of the project>,
    "dataset_id": <name of the project>,
    "description": <project description string>,
    "url": <project url>
}
```

The variable-metadata.json contains:
The tag field is an array of strings. Each string is concatenation of  `key` , `:`  and  `value`.
```
{
    "name": <name of the property>,
    "variable_id": <name of the property>,
    "description": <property description string>,
    "corresponds_to_property: <Pnode name>,
    "tag":  [
        "FactorClass:http://ontology.causeex.com/ontology/odps/ICM#AbilityToAddressBasicNeeds",
        "Relevance:-1.0",
        "Normalizer:Standard",
        "Units:Index",
        "DocID:f3320c85d16ed1913c67be93ca467cee"
    ]
}
```

The annotation.json contains information about the annotations. This file is used generate canonical CSVs from other uploaded CSVs for the same format.

**Comment by g1eb** [comment]
Devora mentioned that this already exists but needs to be tested, is that correct?
Is there and endpoint to download the zip file to test?

**Comment by devowit** [comment]
this does not already exist. there is an endpoint for downloading results as a zip file, but not something that returns this specific format. (if you are able to successfully download from that endpoint, that would mean the backend is sending binary files correctly, and i can just create kethia's zip file and add an endpoint for that)

**Comment by g1eb** [comment]
@devowit are you referring to this endpoint here? ['/api/project/download/<filetype>/<filename>/all'](https://github.com/usc-isi-i2/t2wml/blob/development/backend/application.py#L378)

**Comment by devowit** [comment]
1. name and variable_id are supposed to be the exact same thing? is the name of the property its label?
2. what is corresponds_to_property? the auto-generated property id? (eg Pproject-name-myprop)
3. Am I supposed to assume all those tags are present, or create an array of whatever tags are defined for that variable? if there are other tags besides those listed I should include them as well? 

"name": <name of the property>,
    "variable_id": <name of the property>,
    "description": <property description string>,
    "corresponds_to_property: <Pnode name>,
    "tag":  [
        "FactorClass:http://ontology.causeex.com/ontology/odps/ICM#AbilityToAddressBasicNeeds",
        "Relevance:-1.0",
        "Normalizer:Standard",
        "Units:Index",
        "DocID:f3320c85d16ed1913c67be93ca467cee"
    ]

**Comment by kyao** [comment]
1. Name is the label of the property. variable_id is the property label without special characters, spaces turned into _, and lower cased
2.  Yes, it is the Pnode
3.  Do not assume tags are always present. Only create an array for tags that are defined for that variables. Yes, there maybe other tags besides those listed.
