### ISSUE TITLE
Ability to upload an existing annotations file to a new project to copy the annotations

### ISSUE THREAD

**Issue by g1eb** [usc-isi-i2/t2wml#479]
This would be similar to file upload but we decided to create a separate endpoint.

Functionality of the GUI would be the same for the desktop and web apps.

**Comment by kyao** [comment]
@devowit Would this be simple to implement if we assume the annotation applies directly to the new CSV without any change?

**Comment by devowit** [comment]
@kyao  if so, it already exists, it's just a matter of selecting the sheet and then "add existing annotation"

**Comment by devowit** [comment]
that's separate from the endpoint for Gleb

**Comment by g1eb** [comment]
For the first iteration we'll be working with tabs for sheets and we can keep the annotations in memory and resend for a different tab if the user wants that (and if there are no annotations on that tab yet).

**Comment by zmbq** [comment]
Upload a project zip file, support 2 endpoints:

1. Take project and open it.
2. Import annotations from rpoject - project should have just one annotation file. If it has more, return a 409 error. IF it has none, do not fail.
3. Perform wikification again, including creation of custom nodes for properties.

**Comment by devowit** [comment]
POST `/api/causx/upload/annotation`

**Comment by g1eb** [comment]
Add option to upload files (`.t2wmlz` files in this case) to the main project menu (top left).

**Comment by g1eb** [comment]
Updating the live demo now, this ticket is included in this update
