### ISSUE TITLE
Ability to extend the qualifier of type `time` to span 2 (or 3?) separate columns

### ISSUE THREAD

**Issue by g1eb** [usc-isi-i2/t2wml#480]
For example when you have two separate columns for `year` and `month`.
Suggested fix is to concatenate the values of the two columns if the qualifier block spans two columns.

Example document where this can be tested: 
[two_column_date_example_small.xlsx](https://github.com/usc-isi-i2/t2wml/files/6659903/two_column_date_example_small.xlsx)

**Comment by kyao** [comment]
[iDATABelarus_annotated_with_dataset_metadata.zip](https://github.com/usc-isi-i2/t2wml/files/6767234/iDATABelarus_annotated_with_dataset_metadata.zip)
Data with time spanning two columns

**Comment by g1eb** [comment]
There's 2 options for this to happen:
1. User creates a qualifier annotation block that spans 2 or 3 columns
2. We automatically suggest the 2 or 3 columns with dates as qualifiers

**Comment by devowit** [comment]
advanced functionality continued in #577, #578

the basic functionality has been implemented, so once tested this issue can be closed.

**Comment by kyao** [comment]
Tested
