### ISSUE TITLE
Endpoint for CausX wikification for countries and wikidata items

### ISSUE THREAD

**Issue by g1eb** [usc-isi-i2/t2wml#483]
This endpoint is to be used for wikification of the main subject and qualifier cells/blocks that have type=wikidata item.

**Comment by g1eb** [comment]
@devowit did you say we already have this and you just needed to check where it is? Let me know

**Comment by devowit** [comment]
yes.
there are two endpoints. one is for countries (main subject blocks) ONLY, it uses amandeep's country wikifier code, and it is at `POST api/web/wikify_region` with the usual data parameters added into the url.
 it expects to get a field "selection" and optionally a field "overwrite" (overwrite existing wikification), which is currently set to default False. if we see that actually we always want to/never want to overwrite i can remove that.
 
the other is `POST api/wikinodes`, with usual data parameters added into url.
it expects to get field selection.
it also expects to get field is_property. and if is_property is True, it expects to get field data_type.

**Comment by g1eb** [comment]
For the second endpoint, are you referring [`api/auto_wikinodes`](https://github.com/usc-isi-i2/t2wml/blob/development/backend/application.py#L320)?

I've tested them both, works great!
I'll close the ticket when I'm done connecting them in the web GUI.
