### ISSUE TITLE
Endpoint to create/read/write/delete tags connected to properties

### ISSUE THREAD

**Issue by g1eb** [usc-isi-i2/t2wml#484]
Something that probably already exists in some shape or form, please let me know

**Comment by devowit** [comment]
GET project/entities returns all entities defined for the project, as a dictionary whose keys are the file in which the entities are saved
PUT project/entities expects to receive the field entity_file (which file the entities are saved in) and updated_entries, a dictionary with key (entity id) and value: a dictionary.
the dictionary works as follows:
for any key other than "tags", it just saves the value for that key in kgtk format (some possible keys are P31, label, description, data_type, but it doesn't actually verify)
for tags, it expects to receive an array, and will add a row to the kgtk file for every entry in the array,


for causx the file name could probably just be something fixed I guess?

**Comment by g1eb** [comment]
For the PUT request, are we supposed to send all the entities in the `updated_entries` array? 
Do we need to create an empty `entities.csv` file in the project directory for this to work? I'm getting this error:

![Screen Shot 2021-06-22 at 10 56 17 AM](https://user-images.githubusercontent.com/1916056/122975925-b43dff00-d348-11eb-86b5-e3f1c9ce6968.png)


@devowit if you don't mind, can you share a working example request headers & body?

**Comment by g1eb** [comment]
Tags related API functionality is described in this document: [https://docs.google.com/document/d/1Cq06NM1cQ1p3F-qJXU0jqv0ZK-OhLggeuDiCB_lXPDk/edit#](https://docs.google.com/document/d/1Cq06NM1cQ1p3F-qJXU0jqv0ZK-OhLggeuDiCB_lXPDk/edit#)

**Comment by g1eb** [comment]
@devowit could you double check if that API description is still up to date?

I'm not seeing the PUT request for the `/api/causx/project/entities?<dir>` endpoint in the `causx_application.py` file and the GET request for `/api/causx/project/entities?<dir>` does not return any entity files.
