### ISSUE TITLE
Include country cameo code in CSV download

### ISSUE THREAD

**Issue by kyao** [usc-isi-i2/t2wml#485]
The download CSV file should include `country_cameo` column.

This KGTK edge file contains the mapping from country qnode to cameo IRI.
[country_cameo_exploded.tsv.gz](https://github.com/usc-isi-i2/t2wml/files/6673547/country_cameo_exploded.tsv.gz)

**Comment by devowit** [comment]
this is also exclusively for causx, or needed in general?

**Comment by kyao** [comment]
This is just for casux
