### ISSUE TITLE
CSV download columns

### ISSUE THREAD

**Issue by kyao** [usc-isi-i2/t2wml#486]
The downloaded CSV should have the following columns:

Dataset_id,variable_id,variable,main_subject,main_subject_id,value,time,time_precision,country,country_id,country_cameo,admin1,admin2,admin3,region_coordinate,stated_in,stated_in_id,stated in,FactorClass,Relevance,Normalizer,Units,DocID

Here is a sample CSV file:

[sample.csv.gz](https://github.com/usc-isi-i2/t2wml/files/6673599/sample.csv.gz)

This P625 file contains coordinates for the countries:

[P625-for-regions-exploded-fixed.tsv.gz](https://github.com/usc-isi-i2/t2wml/files/6673621/P625-for-regions-exploded-fixed.tsv.gz)

**Comment by devowit** [comment]
this is for causx? in general?

**Comment by kyao** [comment]
This for causx

**Comment by devowit** [comment]
do you want this in the preview as well, or only in the downloaded file?
for all the fields that we don't have values for, just add the header and have an empty column? or will these fields have values (via the tags?)

**Comment by kyao** [comment]
Please, have this for the preview as well.

All the columns after `stated in` are based on keys (FactorClass,Relevance,Normalizer,Units,DocID) of tags. If the variable does not have tags, then do not add those those columns.

**Comment by zmbq** [comment]
dataset_id is the proejct name
variable is the property label
variable_id is the property label without special characters, spaces turned into _
region_coordinate - map the country code from the region file
admin1, admin2, admin3 - always empty

**Comment by kyao** [comment]
For this example, the `variable_id` should be `internet_penetration`. The `main_subject_id` and `country_id` should be the qnode for the country.

![Screen Shot 2021-06-25 at 4 49 07 PM](https://user-images.githubusercontent.com/1087657/123496532-61c94080-d5dd-11eb-9182-a2f6f279fbf2.png)

**Comment by devowit** [comment]
consolidating with other issues
