### ISSUE TITLE
Inconsistent red triangles while when I click on `Suggest Annotation`

### ISSUE THREAD

**Issue by saggu** [usc-isi-i2/t2wml#490]
Steps to replicate:

1. Create a new project
2. Upload the attached file
3. Click on `Suggest Annotation`
4. No red triangles in column H, I
![image](https://user-images.githubusercontent.com/6811931/122840583-45f92e00-d2af-11eb-8100-fd97da4b95c0.png)
5. Change Region as shown
![image](https://user-images.githubusercontent.com/6811931/122840632-5a3d2b00-d2af-11eb-9e98-84b102949283.png)
Notice the red triangles
6. Change region back to start from `H2`, the red triangles are still there
7. They should have been there from the beginning as there is no property associated
[cdis_usa_japan.csv](https://github.com/usc-isi-i2/t2wml/files/6690025/cdis_usa_japan.csv)

**Comment by devowit** [comment]
yes, suggesting annotation doesn't actually submit the annotation (and get error checks) until the user's next action (in this case, changing the region).  I can change it to submit the annotation from the get-go.
