### ISSUE TITLE
2.10.0-rc1: changing main subject

### ISSUE THREAD

**Issue by kyao** [usc-isi-i2/t2wml#495]
Suggest annotation selects E7:E821 as main subject. Changing main subject to column A causes spinning circle.

![Screenshot 2021-06-21 220811](https://user-images.githubusercontent.com/1087657/122866833-78218480-d2dd-11eb-81f2-3c6095aba956.png)

[CDIS_IOW_IIW_derived_China_Brazil.zip](https://github.com/usc-isi-i2/t2wml/files/6691187/CDIS_IOW_IIW_derived_China_Brazil.zip)

**Comment by devowit** [comment]
is this still happening in 2.10.2?

**Comment by kyao** [comment]
Fixed
