### ISSUE TITLE
Show list of file sheets and open a different sheet in a new tab on select

### ISSUE THREAD

**Issue by g1eb** [usc-isi-i2/t2wml#498]
Show all available sheets (xlsx file) in a separate menu

Open selected sheet in a new browser tab as a new project

**Comment by devowit** [comment]
would a different sheet in the same file belong to the same project and share the same variable definitions as the other sheets? ie should be reusing variables between the sheets?

**Comment by g1eb** [comment]
I would think so yes, let's check with @kyao

**Comment by g1eb** [comment]
This is a duplicate of [https://github.com/usc-isi-i2/t2wml/issues/564](https://github.com/usc-isi-i2/t2wml/issues/564), closing.
