### ISSUE TITLE
Change text color to orange when block should be wikified but is not wikified (yet)

### ISSUE THREAD

**Issue by g1eb** [usc-isi-i2/t2wml#499]
Check for type==Country (used to be wikibase item)

**Comment by g1eb** [comment]
Change wikibaseItem label in the types dropdown menu to Country

**Comment by szeke** [comment]
This will not happen in the causx version because when the type is wikibase-item (country), the system will automatically run the country wikifier and create q-nodes for the cells that don't get wikified, so the user will never see non-wikified cells.

**Comment by g1eb** [comment]
Gotcha, I've changed the label of `Wikidata Item` in the annotation types menu to `Country`.
Closing this for now as the changing colors are not relevant (out-of-scope) for CausX.
