### ISSUE TITLE
PartialCSV endpoint giving errors and we don't know why

### ISSUE THREAD

**Issue by g1eb** [usc-isi-i2/t2wml#501]
After switching to the new causx endpoint for partial CSV the output window does not update on subsequent requests (this is after we created the annotations)

Relevant endpoint:

GET /api/causx/partialcsv?<dir>&<data_params>&<mapping_params>
Expects: nothing
Returns: a table under the key “partialCsv”

**Comment by g1eb** [comment]
File that was used in testing: 
[annotation_example.xlsx](https://github.com/usc-isi-i2/t2wml/files/6719016/annotation_example.xlsx)

**Comment by devowit** [comment]
I'm not sure I understand what you're describing here. What is not updating? The response is returning old results? The response is not returning anything? Spmething else?

**Comment by g1eb** [comment]
The response is only returning the header of the output table, without the rest of the table. For example:

```
{"partialCsv":{"cells":[["dataset_id","variable_id","variable","main_subject","main_subject_id","value","time","time_precision","country","country_id","country_cameo","admin1","admin2","admin3","region_coordinate","stated_in","stated_in_id","stated in","FactorClass","Relevance","Normalizer","Units","DocID"]],"dims":[1,22],"firstRowIndex":0}}
```

**Comment by devowit** [comment]
consolidating with other issues
