### ISSUE TITLE
Inconsistent CSV preview

### ISSUE THREAD

**Issue by kyao** [usc-isi-i2/t2wml#504]
I was able to get country qnode and cameo code columns in a t2wml session. 
![image](https://user-images.githubusercontent.com/1087657/123579004-d93cd280-d78b-11eb-8005-82d251a57c1c.png)

But, in sequent sessions. It's the same data file content. 
![image](https://user-images.githubusercontent.com/1087657/123579258-65e79080-d78c-11eb-9f4c-24d368efaf8f.png)

**Comment by devowit** [comment]
I'm sorry, I don't understand what you're trying to describe here -- can you describe each step you took and what you expected to see?

**Comment by kyao** [comment]
Column E in the first image show country qnodes, while the second show the country labels. 

Column J in the first image shows the country cameo codes, while the second image shows blanks. 

It is as if the call to the wikifier failed?

**Comment by kyao** [comment]
Here is the data file. I uploaded the file, clicked `Suggest Annotations`, select the dependent variable block and created a `quantity` property.  Once I was able to get the country qnodes and cameo codes to show up. But, the other times they failed to show up.

[World Education Index test 4.zip](https://github.com/usc-isi-i2/t2wml/files/6726302/World.Education.Index.test.4.zip)

**Comment by devowit** [comment]
I haven't yet successfully replicated this, i get the cameo codes every time...

**Comment by kyao** [comment]
Are you testing using https://t2wml.isi.edu/ ?

**Comment by devowit** [comment]
no i was testing it against code. @g1eb , has the site been updated with our fixes?

**Comment by devowit** [comment]
consolidating with other issues
