### ISSUE TITLE
Show Property Tags Button

### ISSUE THREAD

**Issue by kyao** [usc-isi-i2/t2wml#506]
Property tags can only be added to properties associated with dependent variables, not qualifiers.

For the Education Index dataset, the `Show Property Tags` button should show up here:
![image](https://user-images.githubusercontent.com/1087657/123821497-4ba6d300-d8b0-11eb-8514-d164dfe5e4d6.png)

But, not here:
![image](https://user-images.githubusercontent.com/1087657/123821746-87419d00-d8b0-11eb-982a-cdcc8a08de4c.png)

**Comment by g1eb** [comment]
done and updated on the live demo website [t2wml.isi.edu](https://t2wml.isi.edu)
