### ISSUE TITLE
Docker for Web T2WML

### ISSUE THREAD

**Issue by kyao** [usc-isi-i2/t2wml#507]
Due July 9

Generate docker for Web T2WML for initial deployment to CX.

**Comment by zmbq** [comment]
Can we have two docker images, one for the backend and one for the frontend, and a docker-compose file that fires both up? Or much we have one docker image (doable, but less docker-friendly)

**Comment by kyao** [comment]
Using docker compose is fine. This version is for other CX performers to annotate data and test uploading the zip file to FIDIL.

**Comment by g1eb** [comment]
Right now we have a Dockerfile for the t2wml-web that builds the react app and serve the built files using nginx (running nginx inside the t2wml-web docker container). Docker build command takes an optional build parameter that can be used to point to the location of the t2wml-backend (default is set to `http://0.0.0.0:13000`), for example:

```
docker build --build-arg REACT_APP_BACKEND_URL=https://t2wml.isi.edu -t t2wml-web .
```

In addition to that we have a `docker-compose.yml` file that builds both t2wml-web and t2wml-backend containers.
To build both images and run them with default settings simply run: `docker compose up -d` from the t2wml-web folder. 

@kyao could you confirm that this would work for Causx?

**Comment by kyao** [comment]
I am able run docker-compose to bring up the two containers and access the t2wml.
