### ISSUE TITLE
support for multiple users

### ISSUE THREAD

**Issue by devowit** [usc-isi-i2/t2wml#508]
and better support for multiple files

**Comment by zmbq** [comment]
Session based separation. Session can be returned in a cookie, so that the frontend doesn't have to do anything. Just return a session cookie. https://developer.mozilla.org/en-US/docs/Web/HTTP/Cookies

**Comment by g1eb** [comment]
@devowit I found a minor bug, it seems like the project directory does not exist if users don't make any annotations. This results in an error when we try to fetch the partial csv output after updating project settings (for example changing project title or description). Here is the error message:

```
Error returned from get_causx_partial_csv: [Errno 2] No such file or directory: '/proj/ec6c5698-809b-45be-86fb-449bdad8c6fd/annotations/annotation_example_canonical.annotation'297
```

**Comment by devowit** [comment]
project directory exists, annotation file doesn't. will fix.
