### ISSUE TITLE
clicking somewhere should not create a block

### ISSUE THREAD

**Issue by devowit** [usc-isi-i2/t2wml#518]

**Comment by g1eb** [comment]
@devowit could you remind me what we settled on as a workaround for this?
Is it okay to open a separate menu and have the user confirm if they want to create that annotation or not?

**Comment by devowit** [comment]
yes, that was what was agreed -- clicking somewhere where there is no block currently (including a larger selection than just one block) -- will get a pop up menu with a "confirm" button. any changes on an existing block (including new block, after first confimrm) get submitted without needing to press button

**Comment by g1eb** [comment]
thanks for the clarification, will work on this tomorrow/wednesday
