### ISSUE TITLE
drop tsv, csv, and json downloads

### ISSUE THREAD

**Issue by g1eb** [usc-isi-i2/t2wml#522]
Remove tsv, csv and json download options from the download menu bottom right

**Comment by g1eb** [comment]
done and updated on the live demo website [t2wml.isi.edu](https://t2wml.isi.edu)

**Comment by kyao** [comment]
Please, add back the tsv download option. We need the tsv to test workflow. To test compatibility they will be adding the tsv to Datamart, and the zip file to FIDIL.

**Comment by kyao** [comment]
@devowit This TSV download file just contains edges related to the dataset metadata. It should contain all the edges.

**Comment by kyao** [comment]
Tested using the deployed version

**Comment by g1eb** [comment]
@kyao not to nitpick or anything but for the original `drop tsv, csv, and json downloads` I simply removed the relevant download option buttons from the GUI.

If you're saying that the downloaded file is not correct I think it should be in a separate github issue.

**Comment by kyao** [comment]
Yes, should have created a separate issue

**Comment by devowit** [comment]
opening a new issue
