### ISSUE TITLE
invalid mapper returning "no values for column300"

### ISSUE THREAD

**Issue by devowit** [usc-isi-i2/t2wml#528]

**Comment by devowit** [comment]
@g1eb  annoyingly I am not managing to replicate this error anymore, even though i thought I knew what sequence of steps to take to get it

**Comment by g1eb** [comment]
That's ok, I'll see if I can narrow it down with better steps to replicate. Any clue what the file300/column300 part means?

**Comment by g1eb** [comment]
I've added an arbitrary delay between each update to the output preview and it seems to have helped..

We can reopen if we run into this issue again.
