### ISSUE TITLE
Add dropdown menu to allow users to select and link a different property

### ISSUE THREAD

**Issue by g1eb** [usc-isi-i2/t2wml#532]
dependent variable annotation menu should have a menu with available property blocks to choose from and link to.

**Comment by g1eb** [comment]
@kyao I found this issue and it has no milestone set, do we still need/want this functionality?

**Comment by kyao** [comment]
@devowit For the educational index dataset, the `HDI Rank` property (cell A4) is closer to qualifier cells A5:A:199, yet it associated with the dependent variable cells starting at C5. Is there a way to tweak the assignment algorithm to make this dataset work?

![image](https://user-images.githubusercontent.com/1087657/129275677-930205f7-ae7a-4e7f-8c8f-265ef8c517bd.png)

**Comment by kyao** [comment]
Have drop down menu for user to pick the right property. Menu item would be a cell index or a cell range.
