### ISSUE TITLE
Output preview does not update if property annotation A2 is made before the suggest annotations/guess blocks request

### ISSUE THREAD

**Issue by g1eb** [usc-isi-i2/t2wml#534]
Getting this error back from the backend:
```
errorDescription: "Error returned from get_causx_partial_csv: Error returned from get_cells_and_columns: 'node1'246341"
```

Here's the `.xlsx` file to reproduce this:
[World Education Index by Country 1234.xlsx](https://github.com/usc-isi-i2/t2wml/files/6772675/World.Education.Index.by.Country.1234.xlsx)

**Comment by devowit** [comment]
i am not managing to replicate the error.

however, i do see that when suggest blocks is returned, the orange notation for property doesn't disappear, even though it has been deleted (well, over-written) from the annotation. why is that?

**Comment by g1eb** [comment]
Suggest annotation button returns the suggested annotations and deletes all other annotations. We should prompt users for a confirmation and remove other non-suggested annotations from the gui.

**Comment by devowit** [comment]
does this still need to be addressed?

**Comment by g1eb** [comment]
We can close this issue, i'm implementing the confirmation in a different ticket #549
