### ISSUE TITLE
Qualifier column not displayed in preview

### ISSUE THREAD

**Issue by kyao** [usc-isi-i2/t2wml#541]
Testing the latest using t2wml.isi.edu.

The `Rank` qualifier column is failing to show up in the preview. This used to work:

![image](https://user-images.githubusercontent.com/1087657/124834089-016ac500-df34-11eb-82af-0e38913eb3ca.png)

**Comment by g1eb** [comment]
The `crop` column also used to show up in the output preview, you can test with this file here:
[annotation_example.xlsx](https://github.com/usc-isi-i2/t2wml/files/6780284/annotation_example.xlsx)

**Comment by devowit** [comment]
whoops this is my bad from when I got rid of the extra ID columns. fixing now.
