### ISSUE TITLE
Suggest annotation returning string type for dependent variables

### ISSUE THREAD

**Issue by kyao** [usc-isi-i2/t2wml#542]
Tested on t2wml.isi.edu.

To reproduce:

-  Upload the education index dataset
- Click `Suggest annotations`
- Click cell `A2` then select the ` CELL A2` tab

![image (4)](https://user-images.githubusercontent.com/1087657/124834482-b43b2300-df34-11eb-9385-78d0aad37a60.png)

**Comment by g1eb** [comment]
@kyao found another issue without a milestone set, is this still relevant?

**Comment by kyao** [comment]
Looks like it has been fixed
