### ISSUE TITLE
Incorrect cell highlighting

### ISSUE THREAD

**Issue by kyao** [usc-isi-i2/t2wml#543]
To reproduce:

- Select cells A5 to A9
- In the `Selected range` box delete the digit `9` and type `199`

As I typed `199` I see a red error box pop up, something about `500` type error. But, I did not have time to read it before it disappeared.

![image](https://user-images.githubusercontent.com/1087657/124843562-084f0300-df47-11eb-97e3-e1133114d400.png)

**Comment by devowit** [comment]
@g1eb  when backspacing the 3 from A5:A13, the selection A5:A1 is submitted, and then the block is A1:A5. meanwhile user continues typing so now its A5:A17, but the block doesnt get updated (maybe becaue there's no longer a block overlapping those coordinates...)
i think you need to add a delay when people are typing before submitting the selection. maybe also don't allow backwards selections (D5:B7, B7:D5, of D6:B7 type combinations)

**Comment by g1eb** [comment]
I've been playing around with different ways of submitting the changes, and so far these 2 seem to work best:
- onBlur (aka when users click anywhere outside the selected range input field)
- on Enter keydown event (if users hit the Return button we submit the changes)

@kyao could you test it out on our demo site and let me know if that works? I can add the timeout back in but it would have to be relatively large timeout for this to work smoothly with selection changes, something around a 1 second timeout worked ok.

**Comment by g1eb** [comment]
Closing for now as discussed during the meeting on July 27.
Please reopen if still buggy after testing.
