### ISSUE TITLE
overlapping causes property issues

### ISSUE THREAD

**Issue by devowit** [usc-isi-i2/t2wml#544]
steps to reproduce:
1. annotate a dependent variable
2. annotate a qualifier block, accidentally overlapping into dependent variable

now, both dependent variable block and qualifier block are assigned P585 as property, and there's no way to remove it from the dependent variable.

(subsequently the frontend crashes...)

**Comment by g1eb** [comment]
Devora i think we looked into this one already and were not able to reproduce it.
Feel free to reopen if this is still happening.
