### ISSUE TITLE
Optional property description for automatically created properties

### ISSUE THREAD

**Issue by kyao** [usc-isi-i2/t2wml#545]
For automatically created properties there is not a way to optionally provide property descriptions:

![image](https://user-images.githubusercontent.com/1087657/124965704-472c9980-dfd7-11eb-8858-eac68e1106b5.png)

Unlike manually created properties:

![image](https://user-images.githubusercontent.com/1087657/124966414-26b10f00-dfd8-11eb-850d-c84df0cdc24d.png)

**Comment by g1eb** [comment]
The same endpoint that is currently used to edit/update property tags can be used to update property descriptions.

We need to add an edit icon button to the cell/wikification overlay menu and pop-up an editable menu for the property.
