### ISSUE TITLE
Remove SUBMIT button in Create a new property pane

### ISSUE THREAD

**Issue by kyao** [usc-isi-i2/t2wml#548]
To make GUI consistent, remove `SUBMIT` button in `Create a new property` pane.

**Comment by devowit** [comment]
or we could add back the submit button when creating new blocks, as discussed during the meeting. 
then the submit button could be renamed to "create new" and it would be consistent across the board.

@g1eb  @szeke ?

**Comment by g1eb** [comment]
Yeah! This also seems to tie in with the "don't create annotations when clicking" issue. We can show a pre-filled annotation menu with our suggestion but only submit as annotation when users click the "submit" or "create new annotation" button.

We discussed this briefly with Pedro and what we could also do is simply not allow users to click outside the create property menu until they are done with the create property form. This way users are forced to either close the menu with the X button in the top right corner (aka cancel) or submit the changes with the submit button.

**Comment by g1eb** [comment]
We discussed not automatically creating annotation blocks and asking users to confirm the annotation suggestion first. In other words, we're going to be adding a confirmation submit button back to the annotation menu and this ticket is no longer relevant.
