### ISSUE TITLE
Web browser caching (Firefox) causes `DOWNLOAD` `ZIP` to download the zip file from a previous session

### ISSUE THREAD

**Issue by kyao** [usc-isi-i2/t2wml#552]
Web browser caching (Firefox) causes `DOWNLOAD` `ZIP` to download the zip file from a previous session

**Comment by g1eb** [comment]
Could you try again with the version deployed over at [https://t2wml.isi.edu/](https://t2wml.isi.edu/)?

(I've set the cache setting to be `no-store` for the download file requests)

**Comment by kyao** [comment]
Fixed
