### ISSUE TITLE
tsv download missing edges

### ISSUE THREAD

**Issue by devowit** [usc-isi-i2/t2wml#553]
@kyao :
> This TSV download file just contains edges related to the dataset metadata. It should contain all the edges.

this sounds like a bug. can you please:
1. describe the steps you took before pressing download tsv?
2. attach the .t2wmlz project file for the project that gave you this issue?

Thanks

**Comment by kyao** [comment]
To replicate use the education index dataset. Do the regular annotations first. Then, the last step is the change dataset description and url.

[World_Education_Index_truncated_1625948867723.zip](https://github.com/usc-isi-i2/t2wml/files/6795909/World_Education_Index_truncated_1625948867723.zip)

**Comment by kyao** [comment]
Here is the partial tsv file:
[World_Education_Index_truncated_1625948725342_tsv.zip](https://github.com/usc-isi-i2/t2wml/files/6795919/World_Education_Index_truncated_1625948725342_tsv.zip)

**Comment by kyao** [comment]
Also, it's not consistent. I tried it again, and this time I got the full tsv.

**Comment by kyao** [comment]
Cannot replicate with current version. Closing the issue for now.
