### ISSUE TITLE
Qnode entries persist after removing an annotation block

### ISSUE THREAD

**Issue by g1eb** [usc-isi-i2/t2wml#555]
After annotating a block as property and sending the annotation in to create auto wikinodes we get our custom property entries back in the layers.

Is it possible to remove these entries when users delete that annotation block? Our wikified cells keep coming back in the layers.

**Comment by g1eb** [comment]
@devowit  do you know if we can remove those wikinodes and/or custom properties in the backend when users delete annotations with those properties?

**Comment by devowit** [comment]
theoretically yet. but why do we want to, though?

**Comment by g1eb** [comment]
I'm not sure, seems like there is no way to unlink them right now. Once the text is blue (meaning wikified) it remains blue even if you remove the annotation block that created those custom pnodes in the first place.

@kyao do we want the custom pnodes removed when that annotation block is removed?

**Comment by kyao** [comment]
I think it would look cleaner if we deleted the custom pnodes when the annotation is removed

**Comment by g1eb** [comment]
We are going to remove the blue text from cells that used to be in an annotation block and are no longer in an annotation block (but may still have custom properties from the previous block)

**Comment by g1eb** [comment]
@devowit correct me if i'm wrong, your suggestion during the meeting was to remove the "blue colored qnode text" if those cells are not part of an annotation block, right?

I'm trying to find a link between the `layers.qnode.entries` as returned from the api and the annotation blocks. Annotations blocks typically have a hash `id` and a `selection` object with the x1/y1 and x2/y2 coordinates. And qnode/pnode layer entities have a list of indices representing cells where they appear. Can we link those qnode layers to the annotation blocks where they appear using the hashed annotation block id?

**Comment by g1eb** [comment]
I created a separate ticket for the performance optimization issue outlined in the previous comment, see [https://github.com/usc-isi-i2/t2wml/issues/592](https://github.com/usc-isi-i2/t2wml/issues/592
)
Updated [https://t2wml.isi.edu/](https://t2wml.isi.edu/) with a workaround on the front-end.

**Comment by devowit** [comment]
i mean i assumed it would be simplest to9 have blue node coloring be conditional on also having block class, no?

**Comment by g1eb** [comment]
It is simple - but it's not the most clear way of doing this. The way that annotations and statement layer entities are separated right now makes this change super "hacky" on the front-end. We should really address this and either fix the linkage between the annotations and statement layer entities - or simply remove properties when users delete the annotation blocks (as was originally stated in the issue).

Let's continue this conversation in this dedicated issue [https://github.com/usc-isi-i2/t2wml/issues/592](https://github.com/usc-isi-i2/t2wml/issues/592)

**Comment by zmbq** [comment]
@Gleb, removing the items from the layer causes all sorts of issues for the non Causx version - including, but not only, the need to wikify a cell twice if the user reinstates the block on that cell. Since we have only one backend for both versions, we really don't want to change it -it will force us to add additional caching mechanisms.

Can't just make the CSS change, that if the background is white, the foreground is black no matter what?

**Comment by g1eb** [comment]
What happens when users create a data type annotation block, change it to a property type annotation (by mistake?) and then change it back to the data type annotation again?

With auto-wikification of property type blocks we would get blue text for that data type annotation block, see screenshot below:

![Screen Shot 2021-08-11 at 11 08 25 AM](https://user-images.githubusercontent.com/1916056/129080878-527bcc17-5feb-4df0-9f88-ae9672ba644c.png)

**Comment by zmbq** [comment]
@devowit , if a cell is in a block that is *not* of type item, a qnode should never be returned for that cell.

**Comment by devowit** [comment]
as discussed previously, for non-causx t2wml wikification is independent from blocks and it is possible for a cell to be wikified and also be a quantity dependent variable. 

for causx, if this is causing so many issues, I can remove the wikification nodes from the results by checking against the annotation blocks.
this can either be by actually deleting them, or simply by removing them from the layer returned to frontend. the only time this makes a practical difference is for properties -- do we keep the tags etc the user input for that property, or do we delete them?

I am currently inclined towards simply removing from the layer.
