### ISSUE TITLE
Cannot scroll right to see the entire spreadsheet

### ISSUE THREAD

**Issue by kyao** [usc-isi-i2/t2wml#558]
Cannot scroll all the way to right to see the entire spreadsheet. Test on Firefox.
[population_indicators_subset_qualifier_parsed_partial.zip](https://github.com/usc-isi-i2/t2wml/files/6845419/population_indicators_subset_qualifier_parsed_partial.zip)

**Comment by g1eb** [comment]
I've been able to fix it for now, let's see if this works as expected on the live demo.
I think the scroll fix Itay suggested during our meeting on Tusday is better for us in the long run.
