### ISSUE TITLE
Generate FIDIL JSON

### ISSUE THREAD

**Issue by kyao** [usc-isi-i2/t2wml#559]
FIDIL organizes dataset at the timeseries level. Assume each FIDIL timeseries can be uniquely specified by the triple (dataset_id, variable_id, country). For the purpose of Causx, except for the time qualifier, ignore qualifiers.  Each uploaded Excel/CSV file can generate one or more timeseries.

FIDIL JSON is an array of timeseries objects, each timeseries object has properties

- id: string, uuid md5 hash of concat(dataset_id, variable_id, country)
- country: string, country label
- country_cameo: string, URI for country
- label: string, variable (property) label
- description: string, concat(document description, variable (property) description)
- excelFile: array of strings, where each string is the name of an uploaded file
- sheet: array of strings, where each string is the name of a sheet. If the uploaded file is CSV, then use the CSV filename without the suffix.
- units: string
- structuredDataMapping, object with properties
  - docID, string
  - factorClass, string
  - normalizer, string
  - relevance, number
  - other-user-defined-keys, string
- structuredData, array of objects, each object with properties
  - timestamp, string in ISO format
  - value, number

**Comment by devowit** [comment]
> excelFile: array of strings, where each string is the name of an uploaded file
> sheet: array of strings, where each string is the name of a sheet. If the uploaded file is CSV, then use the CSV filename without the suffix.

in  a case with N excel files with M sheets, `sheets` contains MxN values?

**Comment by devowit** [comment]
>other-user-defined-keys, string

this is a single key whose string value is concatted from multiple keys, or a filler entry for any other user keys, ie

structuredDataMapping, object with properties
docID: string
factorClass: string
normalizer: string
relevance:number
mykey1: string
mykeyt2: string2

**Comment by devowit** [comment]
attached is an example FIDIL json (from the freedom house press example)

please look at it and let me know if I've built it correctly. Thanks @kyao 

[example_fidil_freedomhousepress.txt](https://github.com/usc-isi-i2/t2wml/files/6874365/example_fidil_freedomhousepress.txt)

**Comment by kyao** [comment]
The file looks good to me. I am sending it to the CX folks to have them take a look.

**Comment by kyao** [comment]
One thing is all the factor classes should have the prefix: `http://ontology.causeex.com/ontology/odps/ICM#`

**Comment by devowit** [comment]
ok, i have pushed the necessary change to add the prefix
