### ISSUE TITLE
Same Location Value in Multiple Columns

### ISSUE THREAD

**Issue by akankshadiwedy** [usc-isi-i2/t2wml#56]
In the attached screenshot, "United Kingdom" in X79 is being mapped correctly according to Qnode in Wikifier file, however same value not being mapped in Y87. 
None of the value in column Y is being mapped despite their values defined with qnodes in wikifier file. (This is not a problem if the values are numeric. They map to multiple columns without such problem)
(To reproduce : The file, wikifier-file, and yaml can be found at https://github.com/akankshadiwedy/Wikidata-UCDP/tree/master/location)

![Screen Shot 2019-11-07 at 3 29 01 PM](https://user-images.githubusercontent.com/11754062/68436661-8310bb00-0173-11ea-97d6-d65d2601fe12.png)

**Comment by bhatiadivij** [comment]
I have pushed a fix. Try reuploading the data and wikified output files to make it work. 
@akankshadiwedy
