### ISSUE TITLE
Add WDI regions to wikifier

### ISSUE THREAD

**Issue by kyao** [usc-isi-i2/t2wml#568]
Add WDI regions to wikifier

**Comment by kyao** [comment]
Here is the list  of country/regions used by WDI
[WDI_country_names.csv.gz](https://github.com/usc-isi-i2/t2wml/files/6889057/WDI_country_names.csv.gz)

**Comment by devowit** [comment]
so even things like "IDA total",  "IDA blend",  "IDA only", "High Income", "Upper middle income", "Late-demographic dividend" you want treated as countries?

**Comment by devowit** [comment]
the total list of new entries to countries:

'Africa Eastern and Southern', 'Africa Western and Central', 
'Central Europe and the Baltics', "Côte d'Ivoire", 'Caribbean small states', 'Curaçao', 
'East Asia & Pacific (excluding high income)', 'Early-demographic dividend', 
'East Asia & Pacific', 'Europe & Central Asia (excluding high income)', 
'Fragile and conflict affected situations', 'High income', 'IBRD only', 'IDA & IBRD total', 
'IDA total', 'IDA blend', 'IDA only', 'Low income', 'Lower middle income', 'Low & middle income', 
'Late-demographic dividend', 'Middle East & North Africa', 'Middle income', 
'Middle East & North Africa (excluding high income)', 'OECD members', 'Other small states', 
'Pre-demographic dividend', 'Pacific island small states', 'Post-demographic dividend', 
'Sub-Saharan Africa (excluding high income)', 'Small states', 'São Tomé and Principe', 
'East Asia & Pacific (IDA & IBRD)', 'Europe & Central Asia (IDA & IBRD)', 
'Latin America & Caribbean (IDA & IBRD)', 'Middle East & North Africa (IDA & IBRD)', 
'Sub-Saharan Africa (IDA & IBRD)', 'Upper middle income'

Tell me if some of them don't belong.

**Comment by kyao** [comment]
Let's just use all of them.

A few of them has cameo codes:
"Côte d'Ivoire": "http://ontology.causeex.com/cameo/CountryCodeOntology/CAMEOciv"
'Curaçao': "http://ontology.causeex.com/cameo/CountryCodeOntology/CAMEOcuw"
'Caribbean small states':  "http://ontology.causeex.com/cameo/CountryCodeOntology/CAMEOcrb"
São Tomé and Principe': "http://ontology.causeex.com/cameo/CountryCodeOntology/CAMEOstp"

**Comment by kyao** [comment]
Tested. Wikified all the WDI "countries".

**Comment by devowit** [comment]
ok, added the cameo codes
