### ISSUE TITLE
Interesting bug with uploading annotations from a previous `.t2wmlz` project file

### ISSUE THREAD

**Issue by g1eb** [usc-isi-i2/t2wml#579]
To reproduce this issue upload a regular file first, add annotations and save the results by downloading the `.t2wmlz` file. 

Step 2 is to upload the same original file again, select `Upload Annotations` from the project menu in the top-left corner, now drag-and-drop (or click and upload) the `.t2wmlz` project file from the previous step.

The result is that the annotations have exactly 3 more annotated cells than before.

(PS. Uploading the saved `.t2wmlz` file straight up from the start works just fine, this issue occurs only when you select the `Upload Annotations` option from the project menu)

Here is the original `.xlsx` file that I was testing with:
[annotation_example.xlsx](https://github.com/usc-isi-i2/t2wml/files/6920188/annotation_example.xlsx)

**Comment by g1eb** [comment]
Here's a picture of what the result looks like with the additional empty cells added to the annotation blocks:

![Screen Shot 2021-08-02 at 5 09 46 PM](https://user-images.githubusercontent.com/1916056/127938426-81cbae69-9787-4b18-bd9b-0a9c4b6c57cf.png)

**Comment by devowit** [comment]
@abhinav-kumar-thakur

**Comment by abhinav-kumar-thakur** [comment]
I am looking at this issue. @g1eb could you also share the annotation file with me. I will use the same for my testing. Till then, I will create my own annotations and try to reproduce the bug.

**Comment by g1eb** [comment]
@abhinav-kumar-thakur would it be possible to remove/trim the empty lines at the end of the new annotations in the picture?

[annotation example.zip](https://github.com/usc-isi-i2/t2wml/files/6926697/annotation.example.zip)

Here is the zip folder of both original input file and the saved `.t2wmlz` project file that I used to upload/copy the annotations from. You can try this on our live demo [https://t2wml.isi.edu/](https://t2wml.isi.edu/) by uploading the original file first and then uploading the annotations via the project menu in the top left of the screen. 

![Screen Shot 2021-08-03 at 12 47 04 PM](https://user-images.githubusercontent.com/1916056/128076839-d4b07f0c-5cbf-4911-b675-8ebc54155cd3.png)

**Comment by g1eb** [comment]
FYI we are going to rename the `Upload Annotations` button to `Apply Annotations` in #582

**Comment by abhinav-kumar-thakur** [comment]
Okay @g1eb,  As per the implementation of copy_annotations it should ignore any row/column which is completely empty. Let me check and get back on why this issue is happening.

**Comment by g1eb** [comment]
thank you!

**Comment by abhinav-kumar-thakur** [comment]
`copy_annotation` function excepts both the source and target Dataframe to have the empty cells represented by **NaN**. So, that it can ignore them while copying the annotations.

While debugging I found that the expectation is met by the source_df argument to the` copy_annotation` function.
![image](https://user-images.githubusercontent.com/14326083/128087026-375196da-a0dd-4360-b411-9f852d572edb.png)

But, the target_df has the empty cells as a blank string i.e. `""`.
![image](https://user-images.githubusercontent.com/14326083/128087169-2f96ba6a-8e5e-4689-8e23-2e773d946830.png)

We can make target_df as same as source_df to fix this issue.

**Comment by g1eb** [comment]
Updated on our live demo to include this PR ^ [https://t2wml.isi.edu/](https://t2wml.isi.edu/)
