### ISSUE TITLE
Wikifier GUI does not show label and description

### ISSUE THREAD

**Issue by saggu** [usc-isi-i2/t2wml#58]
I am running the `t2wml` GUI locally. When I try to wikify some cell values, the `wikifier` GUI does not show the label and descriptions for the QNODES
![image](https://user-images.githubusercontent.com/6811931/70003826-3f626480-1519-11ea-935b-70961d069aa8.png)

Upon further inspection, it looks like the browser is not sending the request at all,
![image](https://user-images.githubusercontent.com/6811931/70003855-5739e880-1519-11ea-8cbc-020fdb2aca83.png)

The SPARQL endpoint seems to be working btw, confirm that by clicking here,
https://dsbox02.isi.edu:8888/bigdata/namespace/wdq/sparql?format=json&query=SELECT%20%3Fqnode%20%28MIN%28%3Flabel%29%20AS%20%3Flabel%29%20%28MIN%28%3Fdesc%29%20AS%20%3Fdesc%29%20WHERE%20%7B%0A%20%20VALUES%20%3Fqnode%20%7B%20wd%3AQ213854%20wd%3AQ9488%20wd%3AQ470774%20wd%3AQ16227998%20wd%3AQ137669%20wd%3AQ3520045%20wd%3AQ2003153%20wd%3AQ2721457%20wd%3AQ21622311%20wd%3AQ7487024%20wd%3AQ142613%20wd%3AQ3522062%20wd%3AQ7487531%7D%0A%20%20%3Fqnode%20rdfs%3Alabel%20%3Flabel%3B%20%3Chttp%3A%2F%2Fschema.org%2Fdescription%3E%20%3Fdesc.%0A%20%20FILTER%20%28langMatches%28lang%28%3Flabel%29%2C%22EN%22%29%29%0A%20%20FILTER%20%28langMatches%28lang%28%3Fdesc%29%2C%22EN%22%29%29%0A%7D%0AGROUP%20BY%20%3Fqnode

The `Wikifier` GUI component seems to be at fault, I tried this in Chrome and Firefox. Pedro tried it in Safari.

Please take a look

**Comment by szeke** [comment]
Works in current version
