### ISSUE TITLE
Add loading indicator to the apply annotations file upload

### ISSUE THREAD

**Issue by g1eb** [usc-isi-i2/t2wml#587]
It takes some time for the file upload request to come back, we need an indicator showing the user that there's something going on and they need to be patient.

**Comment by g1eb** [comment]
Also need to double check if the annotations get applied if users close the file upload window.
We can disable that, however if the user clicks out of the file upload dialog or closes it in the middle of the upload - perhaps they _do_ want to cancel that upload?

**Comment by kyao** [comment]
I think closing upload dialog would mean cancel, but clicking out side of the dialog would not. Does this seem reasonable?

**Comment by g1eb** [comment]
yeah, makes sense, we'll do that
