### ISSUE TITLE
Instantiable Factor Classes

### ISSUE THREAD

**Issue by kyao** [usc-isi-i2/t2wml#588]
CX wants to be able to distinguish between instantiable factor classes (user created factor classes) and pre-defined factor classes in the ontology. 

The instantiable factor class value should be the string provided by the user without the `http://ontology.causeex.com/ontology/odps/ICM#` prefix. The pre-defined factor class should be an IRI with the prefix.

**Comment by devowit** [comment]
...we allow the user to create factor classes? I thought factor classes was from a drop down?

**Comment by kyao** [comment]
The drop down would contain the pre-defined factor classes. And, these factor classes should have the prefix added.

If the user types in a factor not in the drop down, then the prefix should not be added.

**Comment by devowit** [comment]
so it's a text input + drop down? 
there can only be one factor class, or they can add multiple?

**Comment by kyao** [comment]
Yes, text input + drop down. The gui has already been implemented.
Only one factor class per property.

**Comment by devowit** [comment]
okay so there are two ways I could do this:

1. copy the list of official factor classes into the backend, check if factor class is in that list, if it is apply, prefix (my preferred solution, but means we need to maintain the list in two locations, or have both backend and frontend load from the same file...)
2. have @g1eb send me a flag whether a factor class was a text input or from the dropdown... I think this solution has a lot more problems associated.

**Comment by devowit** [comment]
ok. i'm just using the pre-defined factor class list from t2wml-web and checking against that, so f that changes I will need to update in the backend as well.

I've pushed the change to causx branch

**Comment by devowit** [comment]
someone please update me on whether this can be marked as done @g1eb  @kyao

**Comment by kyao** [comment]
Seems to be working fine

**Comment by kyao** [comment]
Add confirmation if user is creating a new factor class

**Comment by g1eb** [comment]
We discussed this with Ke-Thia and implemented this type of UI for users when they enter an option that is not pre-defined.

![Screen Shot 2021-09-01 at 3 22 50 PM](https://user-images.githubusercontent.com/1916056/132067386-e6e19d8d-d08a-41df-8008-b6fc11765d06.png)

**Comment by g1eb** [comment]
Reopening because now that the custom input works the dropdown selection does not

**Comment by kyao** [comment]
Fixed
