### ISSUE TITLE
Sometime popup closes by itself

### ISSUE THREAD

**Issue by kyao** [usc-isi-i2/t2wml#589]
This problem seems to happen randomly. I am not sure if there is a pattern.

For the education dataset, select the first few cells, say A5:A10. Then, click in the `Selected range` box of the popup window and edit the string to changed it to "A5:A199". Sometimes the popup window would close while I am editing.

Sometimes clicking on the `+ ADD A NEW PROPERTY` button would cause the popup to close.

**Comment by g1eb** [comment]
I've noticed that! So strange, it is recent so must have started with one of the later changes. I'll take a look

**Comment by g1eb** [comment]
Found the bug, it was related to that you can't compare objects for equality in javascript.

```
{x1: 2, x2: 2, y1: 4, y2: 19} === {x1: 2, x2: 2, y1: 4, y2: 19}
false
```
