### ISSUE TITLE
Copy annotations color bug

### ISSUE THREAD

**Issue by devowit** [usc-isi-i2/t2wml#590]
to replicate:

1. load data.xlsx 
[data.xlsx](https://github.com/usc-isi-i2/t2wml/files/6936573/data.xlsx)

2. suggest annotation
3. add the property block
4. save t2wmlz file
5. once again, load dataset.xlsx
6. select "Copy annotation". choose previouly saved file.

the property block is colored purple instead of orange, and initially seems to be treated like a qualifier block -- no partial csv preview. i clicked it, it opened with "property" selected in role dropdown. i switched away from property and then back to property, and this successfully triggered the partial csv loading, but the block remained purple colored.

**Comment by devowit** [comment]
[data.xlsx](https://github.com/usc-isi-i2/t2wml/files/6936569/data.xlsx)

**Comment by g1eb** [comment]
Yeah, I've seen this happen before as well, can't place where it's coming from, will take a look tomorrow.

**Comment by g1eb** [comment]
I can't reproduce this one, is it possible that it was recently fixed a long with other issues?

**Comment by devowit** [comment]
it's possible. I'll close it, and reopen it if I see it happen again.
