### ISSUE TITLE
Do not allow users to create two annotation blocks with the exact same selected area

### ISSUE THREAD

**Issue by g1eb** [usc-isi-i2/t2wml#602]
This one originates from [https://github.com/usc-isi-i2/t2wml/issues/593](https://github.com/usc-isi-i2/t2wml/issues/593) 

We need to add backend validation to check for multiple annotations that could have the exact same selected area.

**Comment by devowit** [comment]
this has been pushed in t2wml-api, can be moved to done once checked and published...
