### ISSUE TITLE
Add tags to the qnode statement layers

### ISSUE THREAD

**Issue by g1eb** [usc-isi-i2/t2wml#604]
Current situation: we get the qnode statement layers in the `/api/causx/auto_wikinodes` response, but they don't have property tags and we have to fetch them separately.

Preferable fix: can we add these tags to the qnode statement layers so as to avoid additional requests?

**Comment by devowit** [comment]
please check if what I've pushed to development fixes this for you...

**Comment by g1eb** [comment]
Okay, I'm updating the frontend and backend containers right now, will report back after the test

**Comment by g1eb** [comment]
Yeah! This is great, I think we can close this ticket now.
