### ISSUE TITLE
Downloaded project file has wrong suffix

### ISSUE THREAD

**Issue by kyao** [usc-isi-i2/t2wml#611]
The downloaded project file has suffix .zip, instead of .t2wmlz.

**Comment by g1eb** [comment]
I can not reproduce this issue, if I click to download `Saved Project (.t2wmlz)` it does download the saved project with the `.t2wmlz` extension, see screenshot below:

![Screen Shot 2021-08-23 at 10 54 37 AM](https://user-images.githubusercontent.com/1916056/130494197-e4dfaea9-bf86-4e94-84d3-c3faab649676.png)

![Screen Shot 2021-08-23 at 10 56 29 AM](https://user-images.githubusercontent.com/1916056/130494284-808e6553-47d5-42c5-800c-c850c0eef2a1.png)

**Comment by kyao** [comment]
I just tested against t2wml.isi.edu. I am still getting a zip file instead of t2wmlz. If it makes a difference, I am using Chrome on Windows.

[internet_penetration_rate_1629742034802.zip](https://github.com/usc-isi-i2/t2wml/files/7033990/internet_penetration_rate_1629742034802.zip)

**Comment by kyao** [comment]
Interesting. On Opera I am getting the correct behavior with a t2wmlz file.

**Comment by kyao** [comment]
For Chrome, I closed the browser and cleared cache, but problem still persists.

**Comment by g1eb** [comment]
hm that is strange, let me try it with your file
