### ISSUE TITLE
Edit property popup window appears partially off screen

### ISSUE THREAD

**Issue by kyao** [usc-isi-i2/t2wml#612]
The `Edit property` popup appears partially off screen. And, there does not seem to a way to move the popup window.
This occurs on Chrome and Opera browsers.

![image](https://user-images.githubusercontent.com/1087657/130161289-f73b64eb-ee92-4f67-82d0-c32992ed76e4.png)

**Comment by g1eb** [comment]
Ke-Thia, what is the screen resolution in the screenshot above? I'm trying to replicate the layout where the menu appears (partially) off-screen. Draggable issue has been fixed already, at least you should be able to move the menus around.
