### ISSUE TITLE
Property description and tags not restored from saved project

### ISSUE THREAD

**Issue by kyao** [usc-isi-i2/t2wml#618]
Property description and tags are not restored from saved project. The same thing happens for `apply annotations`. The project description and tags are lost as well.

To replicate:
+ load education index dataset
+ click on suggest annotation
+ click on cell A2 and create the property
+ click on cell A2 again to 1) add property description and 2) define some tags
+ download .t2wmlz project file
When restoring this project file, cell A2 is highlighted yellow as property. But, clicking on it the description is missing. And, clicking on the `show property tags` button brings the popup window in a strange state.

**Comment by devowit** [comment]
when doing copy annotation we expect to copy properties as they are?

**Comment by g1eb** [comment]
Property description is either not exported with `.t2wmlz` files or not restored to what it was before.

For the property tags I've added a workaround as described in this comment: https://github.com/usc-isi-i2/t2wml/issues/623#issuecomment-910771325

**Comment by devowit** [comment]
i have fixed this for loading projects, it is merged to development

@kyao , isn't the goal of copying annotations copying the structure? can't the property change between copies, ie in one sheet it's "education level" and in another it's "average score"? in such a case copying the properties over would generate wrong results....

**Comment by devowit** [comment]
@kyao, should i copy properties with annotations always, or not?

**Comment by kyao** [comment]
fixed

**Comment by devowit** [comment]
note: this has specifically been reopened because currently, applying an existing annotation does not copy that annotation's properties.

**Comment by devowit** [comment]
so I'm closing this in favor of #642  which is clearer
