### ISSUE TITLE
Add tooltips for the various input fields and selectors throughout the app

### ISSUE THREAD

**Issue by g1eb** [usc-isi-i2/t2wml#619]
This issue is based on the feedback directly from the causx. We need to add (?) icons with tooltips to the labels next to the various input fields and selectors throughout the app.

**Comment by kyao** [comment]
@g1eb Let's talk on Monday to discuss what is the best approach

**Comment by g1eb** [comment]
@kyao Ke-Thia, I've attached a mock-up of what the tooltips would look like, let me know if you approve.

![Screen Shot 2021-09-03 at 5 15 47 PM](https://user-images.githubusercontent.com/1916056/132076043-556eecc6-395d-41ab-9083-29080f73e468.png)

If you approve, we can schedule a meeting and go over the other input fields and add the help icons + tooltips in.

**Comment by kyao** [comment]
The tooltips looks good to me

**Comment by kyao** [comment]
Here are the tool tips for the normalizers:
Simple: scales the data between the minimum and maximum data in the data set
Standard: maps data values to percentile in the data set
Longitudinal: maps data values to percentile by year in the data set

**Comment by g1eb** [comment]
@kyao @szeke I've added a file for the tooltip content here: https://github.com/usc-isi-i2/t2wml-web/blob/develop/src/content/tooltips.js

**Comment by g1eb** [comment]
This is already up on the demo platform: [https://t2wml.isi.edu/](https://t2wml.isi.edu/)

We can keep adding more tooltips and refine the descriptions in the [tooltips content file](https://github.com/usc-isi-i2/t2wml-web/blob/develop/src/content/tooltips.js) as necessary.

@kyao note that I've updated the multiline descriptions with some inline html tags to improve the visuals.
