### ISSUE TITLE
The backend does not uses the updated sparql endpoint when the user changes it from the GUI

### ISSUE THREAD

**Issue by saggu** [usc-isi-i2/t2wml#62]
This happens when trying to `download` triples.

Steps:
1. Start the application, download the triples.
2. Change the sparql endpoint from the GUI and try to download the triples again
3. The backend still uses the first endpoint

**Comment by bhatiadivij** [comment]
@saggu I tried mimicking the issue but it works fine on my end.

**Comment by szeke** [comment]
Works in current release.
