### ISSUE TITLE
Suggest Annotation returns overlapping regions

### ISSUE THREAD

**Issue by kyao** [usc-isi-i2/t2wml#626]
To reproduce, upload this csv file and click on suggest annotations.

[UN_Median_Population_Age-Original.csv](https://github.com/usc-isi-i2/t2wml/files/7126174/UN_Median_Population_Age-Original.csv)

**Comment by g1eb** [comment]
This is the returned error message:

```
errorCode: 400
errorDescription: "Overlapping selections"
errorTitle: "InvalidAnnotationException"
```

**Comment by g1eb** [comment]
I'm also getting this error when upload this file:

[World_Education_Index_truncated_1628029457101.t2wmlz.zip](https://github.com/usc-isi-i2/t2wml/files/7140250/World_Education_Index_truncated_1628029457101.t2wmlz.zip)

**Comment by kyao** [comment]
Also, getting overlapping annotations for this file:

[WGI-Data-modify-dates.zip](https://github.com/usc-isi-i2/t2wml/files/7155952/WGI-Data-modify-dates.zip)

**Comment by devowit** [comment]
Okay, think this has been fixed more thoroughly now (and along the way fixed another bug in the suggestion algorithm)

**Comment by devowit** [comment]
can this be closed?

**Comment by kyao** [comment]
Fixed
