### ISSUE TITLE
With multiple sessions T2WML loses track of uploaded files

### ISSUE THREAD

**Issue by kyao** [usc-isi-i2/t2wml#630]
With multiple sessions T2WML loses track of uploaded files

To replicate:
+ open t2wml tab and upload WGI dataset
+ open another t2wml tab and update UN Median population dataset, and click suggest annotations
+ go back to first tab with WGI dataset and click suggest annotations. T2WML complains that no file is associated with project

**Comment by devowit** [comment]
this is due to a problem with how the session tokens are handled in the frontend

**Comment by zmbq** [comment]
The frontend probably stores the session in `localStorage`. It should either be in an app-based store, or in `sessionStorage`
