### ISSUE TITLE
Error 500 in our suggest annotations endpoint

### ISSUE THREAD

**Issue by g1eb** [usc-isi-i2/t2wml#632]
I'm getting the following error when trying the suggest annotation endpoint on the 1.8mb WGI_Data.csv

```
errorCode: 500
errorDescription: "cannot unpack non-iterable NoneType object"
errorTitle: "TypeError"
```

**Comment by g1eb** [comment]
Here is the file in question:

[Uploading WGI_Data.csv…]()

**Comment by devowit** [comment]
related to #626

**Comment by devowit** [comment]
can this issue be closed now?
