### ISSUE TITLE
Request to suggest annotations hangs forever, until another request of some kind is sent

### ISSUE THREAD

**Issue by devowit** [usc-isi-i2/t2wml#633]
**To Reproduce**
1. Click suggest annotations
2. Wait around until you're sick of waiting
3. Make some other request, like annotating a property, or changing the project description
4. Suggest annotation stops hanging and returns

**Comment by g1eb** [comment]
I can't reproduce this on my end, both locally and on https://t2wml.isi.edu/ 

Can you share the specific file where this is happening? Or does it happen for any file?

**Comment by devowit** [comment]
appears to be resolved
