### ISSUE TITLE
Need options for the P585 precision and format dropdown menus

### ISSUE THREAD

**Issue by g1eb** [usc-isi-i2/t2wml#634]
We discussed adding dropdown menus for the P585 `precision` and `format` menus.
@kyao could you point me to where we can get these options? Thanks!!

**Comment by kyao** [comment]
For precision options are: year, month, day
Internally the options map to: 9, 10, 11

**Comment by g1eb** [comment]
Ke-Thia, just to clarify, do you mean `year=9`, `month=10` and `day=11`?

**Comment by kyao** [comment]
Yes, that is correct

**Comment by g1eb** [comment]
Sounds good, I'll add the dropdown menu with those options for the `precision`. 
Do you have any pointers on where to get the options for the `format` dropdown menu?

**Comment by kyao** [comment]
Let's use these date formats in the dropdown menu. The user should be able to enter other formats. 

- %Y  (2021)
- %Y-%m (2021-09)
- %Y-%m-%d (2021-09-17)
- %d/%m/%Y (17/09/2021)
- %Y-%b-%d (2021-Sep-17)
- %Y-%b-%d (2021-September-17)
- %Y-%m-%dT%H:%M:%S (2021-09-17T14:00:00)

**Comment by kyao** [comment]
For the precisions it looks like t2wml will automatically convert the stings to integers (year -> 9). 
@devowit Is this correct?

**Comment by g1eb** [comment]
@devowit I'm getting an error when trying to save these date format values, do we need to wrap them in quotes?

```
errorCode: 500
errorDescription: "Error returned from get_causx_partial_csv: while scanning for the next token\nfound character '%' that cannot start any token\n  in \"<unicode string>\", line 15, column 23:\n                  format: %Y\n                          ^300"
errorTitle: "ValueError"
```

**Comment by devowit** [comment]
yes, needs to be wrapped in quotes because internally everything gets converted to yaml and yaml treats % as a special character.....

**Comment by g1eb** [comment]
gotcha, that's what I did to get it to work, we can close this ticket I think
