### ISSUE TITLE
Duplicate/wrong label for property

### ISSUE THREAD

**Issue by kyao** [usc-isi-i2/t2wml#637]
Cells G1:H1 are annotated as properties. The property for cell H1 got the label for cell G1.

The same thing happened for cells E1:F1, where were annotated a block of properties.

Tested on desktop version. But, I think the same error is occurring for web version.

![image](https://user-images.githubusercontent.com/1087657/134093357-6c39f0d9-58d3-41a6-9c7b-a2712062d986.png)

[rare-earth-2.zip](https://github.com/usc-isi-i2/t2wml/files/7199285/rare-earth-2.zip)

**Comment by kyao** [comment]
Same bug as #638 ?

**Comment by devowit** [comment]
yes, this is the same bug as #638 
it is fixed in usc-isi-i2/t2wml-api@e396252e0e2c36c533eddc3712614c956ea76352

**Comment by kyao** [comment]
fixed
