### ISSUE TITLE
Internal server on suggest annotations

### ISSUE THREAD

**Issue by kyao** [usc-isi-i2/t2wml#639]
![image](https://user-images.githubusercontent.com/1087657/134436306-d5b024b9-4037-4d67-9851-5f4a4a18c5e1.png)

![image](https://user-images.githubusercontent.com/1087657/134967033-c428732f-9a4d-4f7c-8d5e-349e0f543ae5.png)

Here is the dataset:

[WGI_Data.zip](https://github.com/usc-isi-i2/t2wml/files/7238562/WGI_Data.zip)

**Comment by devowit** [comment]
fixed in usc-isi-i2/t2wml-api@b2c8797959f52d5461c790937c33c4ea5d674912

**Comment by kyao** [comment]
fixed
