### ISSUE TITLE
JSONDecodeError on annotating property column

### ISSUE THREAD

**Issue by kyao** [usc-isi-i2/t2wml#640]
On annotation column c as properties:

![image](https://user-images.githubusercontent.com/1087657/134967595-d1e15c53-8527-4509-908e-4ad3bc116b95.png)

The backend reports json decode error:

![image](https://user-images.githubusercontent.com/1087657/134967288-12350e82-0c93-4b0c-b7c8-8ba1beaaefc5.png)

[WDI-SP_1632768044584.t2wmlz.zip](https://github.com/usc-isi-i2/t2wml/files/7238566/WDI-SP_1632768044584.t2wmlz.zip)

**Comment by devowit** [comment]
I am not able to replicate this -- maybe it was fixed while fixing other bugs...

**Comment by kyao** [comment]
Looks like it is fixed
