### ISSUE TITLE
Exception on /call_wikifier_service

### ISSUE THREAD

**Issue by xphd** [usc-isi-i2/t2wml#70]
There was an exception when I tried to use the tool. Do you have an idea what the issue is?

![screenshot](https://user-images.githubusercontent.com/26799638/72360866-8fa71780-36be-11ea-99a6-87c47d273777.png)

**Comment by bhatiadivij** [comment]
It arises when you access the wikifier service outside ISI. Try using ISI's VPN, it should work.

**Comment by szeke** [comment]
I asked Amandeep to deploy a wikifier that works without vpn. Will take a couple of days.

**Comment by saggu** [comment]
I have added the public URL for wikifier service - https://dsbox02.isi.edu:8888/wikifier/wikify

**Comment by szeke** [comment]
close?
