### ISSUE TITLE
T2WML GUI does not work in Chrome, both master and dev branches

### ISSUE THREAD

**Issue by saggu** [usc-isi-i2/t2wml#72]
The browser only shows a blank page with errors in console

![image](https://user-images.githubusercontent.com/6811931/72480993-eb040300-37ad-11ea-9d35-82bb2864775d.png)

**Comment by bhatiadivij** [comment]
Please try running it again after clearing browser cache for `localhost` and deleting everything in the `<t2wml-project-directory>/config` directory.
@saggu

**Comment by saggu** [comment]
I cloned the t2wml repo into a new folder, and disable cache for browser, still it shows a blank page

![image](https://user-images.githubusercontent.com/6811931/73015390-c4a71e80-3dd0-11ea-8415-a94a9d59e193.png)

**Comment by bhatiadivij** [comment]
I'm not able to figure out why it's not working on your device. I just tested it and everything works on my system.

**Comment by szeke** [comment]
<img width="1680" alt="image" src="https://user-images.githubusercontent.com/1074599/73037433-0958a700-3e1d-11ea-8305-43be9d7b6682.png">
