### ISSUE TITLE
TTL for fertilizer data is incomplete

### ISSUE THREAD

**Issue by szeke** [usc-isi-i2/t2wml#74]
There are two problems. One in interactive mode, where no file is produced. In batch mode, most of the data is missing. The files are:

* Data: https://github.com/usc-isi-i2/ethiopia-experiment/blob/master/restricted/fertilizer/input/Input_Fertilizer_Maize_CSAdata-20140226.xls
* wikifier: https://github.com/usc-isi-i2/ethiopia-experiment/tree/master/restricted/fertilizer
* YAML: https://github.com/usc-isi-i2/ethiopia-experiment/blob/master/restricted/fertilizer/fertilizer_dap.yaml

For some strange reason the interactive and batch behavior are different, and in the TTL most of the data is missing.

**Comment by szeke** [comment]
@kyao Please post the TTL file for DAP

**Comment by bhatiadivij** [comment]
The issue was that the T2WML was not able to identify the type of the property P1200238 which I believe was not present in the wikidata and also in the local property-type map. I have added the type in the local file which resolved the error. Also, the exception which was raised was not too descriptive, I have updated that as well.

**Comment by saggu** [comment]
@szeke @kyao I dont see a `new_properties.yaml`/`new_properties.ttl` file for fertilizer data in the ethiopia-experiment repo, did someone create `P1200238` ? We need to upload the ttl to Wikidata for the ttl generation to work.

Also I see a `datamart` folder but no `output` folder, if someone created ttl files (to be uploaded to wikidata), please also push them to github

**Comment by szeke** [comment]
close?

**Comment by saggu** [comment]
Yup, added missing files. Closing
