### ISSUE TITLE
Not able to use GUI in Chrome browser on Windows

### ISSUE THREAD

**Issue by kyao** [usc-isi-i2/t2wml#77]
Using a Chrome browser on Windows, I get the following error:

![idpiframe](https://user-images.githubusercontent.com/1087657/73470658-143f9a00-433d-11ea-9950-8dae999aa401.png)

If I ignore the error and click on `Log in with Google`, I get this error:
![error](https://user-images.githubusercontent.com/1087657/73471755-bca22e00-433e-11ea-9f7c-a236f75687a1.png)

Also, I have allowed all cookies and reset the browser cache.

**Comment by bhatiadivij** [comment]
Use `http://localhost:5000` to access the GUI and not `http://127.0.0.1:5000`

**Comment by kyao** [comment]
Using localhost worked, thank you.

The print out after running `python application.py` says `http://127.0.0.1:5000`. This needs to be change.

**Comment by bhatiadivij** [comment]
I am totally aware of it but I'm not sure if it can be changed as it logs the IP address, but I'll look into it again. Thanks.
