### ISSUE TITLE
YAML Section Line Highlighting Bug

### ISSUE THREAD

**Issue by bhatiadivij** [usc-isi-i2/t2wml#9]
Different line number and line are highlighted when a line number is clicked.
![Annotation 2019-07-03 182933](https://user-images.githubusercontent.com/25511720/60633644-88728900-9dc0-11e9-9ee7-9ec769657ec0.jpg)

**Comment by JiashengWu** [comment]
@bhatiadivij I've tested Sublime and VS Code, and they all behaved the same as this. I suppose it's intended to do so.

**Comment by bhatiadivij** [comment]
Oh. I see. I think you are right.
