### ISSUE TITLE
New_T2WML system caching issue

### ISSUE THREAD

**Issue by bhatiadivij** [usc-isi-i2/t2wml#96]
The system caches the json/ttl files and the cached ones are downloaded even after applying a new YAML.

**Comment by devowit** [comment]
what commit/branch is this happening in? I stopped having this issue with commit 6f29d08...

**Comment by bhatiadivij** [comment]
I faced the issue in [`bf399f1b14e01cda25e8095e7082c7a553a6fe02`](https://github.com/usc-isi-i2/t2wml/commit/bf399f1b14e01cda25e8095e7082c7a553a6fe02)

**Comment by devowit** [comment]
I have not been able to successfully reproduce this issue. 

Can you give a step-by-step description of the steps taken to reproduce this bug?

**Comment by bhatiadivij** [comment]
I tried to replicate the issue on version 2.0a3 and it seem to have fixed now.
