### ISSUE TITLE
500 Internal Server Error while downloading file

### ISSUE THREAD

**Issue by bhatiadivij** [usc-isi-i2/t2wml#99]
There are 2 versions of this error:
1. Uncaught Error 500: This occurs when I try to download the file and the file is already present in the cache. 
2. Caught Error 500: This occurs when cache is not used and a new file is generated to download and none of the cells raise an error while generating the statement.

I have fixed the error in `Branch_json_tests`. Please refer to this commit for details.
https://github.com/usc-isi-i2/t2wml/commit/84dc237b938ab108342157acddac1601ba58652d

**Comment by devowit** [comment]
has also been fixed in branch staging
